### ISSUE TITLE
🐛 [Paperless] Does not start 2.0.0.1-5test - OCR Output mode not valid

### ISSUE THREAD

**Issue by cnru** [alexbelgium/hassio-addons#1085]
### Description

Install plain Version of Paperless 2.0.0.1-5test

### Reproduction steps

```bash
1. Start Paperless 2.0.0.1-5test
2. Will not start as it caused a ERROR OCR Output mode is not valid
```

### Addon Logs

```bash
-----------------------------------------------------------
 Add-on version: 2.0.0.1-5test
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.1  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.11.2
 Home Assistant Supervisor: 2023.11.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
-----------------------------------------------------------
 Provided by: https://github.com/alexbelgium/hassio-addons 
-----------------------------------------------------------
 Defining permissions for main user : 
User UID: 0
User GID : 0
-----------------------------------------------------------
/etc/cont-init.d/00-global_var.sh: executing
CONFIG_LOCATION='/config/config.yaml'
OCRLANG='ENG FRA GER'
PAPERLESS_OCR_MODE='skip'
PGID='0'
PUID='0'
certfile='fullchain.pem'
keyfile='privkey.pem'
ssl='true'
Timezone set from Etc/UTC to Europe/Berlin
/etc/cont-init.d/00-local_mounts.sh: executing
/etc/cont-init.d/00-smb_mounts.sh: executing
/etc/cont-init.d/01-config_yaml.sh: executing
Load environment variables from /config/config.yaml if existing
---------------------------------------------------------
Wiki here : github.com/alexbelgium/hassio-addons/wiki/Add‐ons-feature-:-add-env-variables
PAPERLESS_OCR_LANGUAGE='eng'
PAPERLESS_OCR_MODE='skip'
/etc/cont-init.d/01-custom_script.sh: executing
Execute /config/paperless-ng.sh if existing
Wiki here : github.com/alexbelgium/hassio-addons/wiki/Add-ons-feature-:-customisation
---------------------------------------------------------
... no script found, exiting
/etc/cont-init.d/20-migration_config.sh: executing
/etc/cont-init.d/31-nginx.sh: executing
[23:27:15] FATAL: PAPERLESS_URL not set, you won't be able to access your site (CSRF error)
/etc/cont-init.d/99-run.sh: executing
[23:27:15] INFO: Defining variables
[23:27:17] INFO: Defining database
[23:27:17] INFO: Using sqlite as database driver
PAPERLESS_DATA_DIR="/config/data"
PAPERLESS_MEDIA_ROOT="/config/media"
PAPERLESS_CONSUMPTION_DIR="/config/consume"
PAPERLESS_EXPORT_DIR="/config/export"
USERMAP_UID="0"
USERMAP_GID="0"
PAPERLESS_OCR_LANGUAGES="eng fra ger"
PAPERLESS_OCR_MODE=""skip""
PAPERLESS_ADMIN_PASSWORD="admin"
PAPERLESS_ADMIN_USER="admin"
[23:27:18] INFO: Starting redis
[23:27:18] INFO: Starting nginx
[23:27:18] INFO: Initial username and password are admin. Please change in the administration panel of the webUI after login.
 
Starting the upstream container
 
Paperless-ngx docker container starting...
Installing languages...
438:C 21 Nov 2023 23:27:18.075 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
438:C 21 Nov 2023 23:27:18.075 # Redis version=7.0.11, bits=64, commit=00000000, modified=0, pid=438, just started
438:C 21 Nov 2023 23:27:18.076 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
438:M 21 Nov 2023 23:27:18.078 * monotonic clock: POSIX clock_gettime
438:M 21 Nov 2023 23:27:18.080 * Running mode=standalone, port=6379.
438:M 21 Nov 2023 23:27:18.081 # Server initialized
438:M 21 Nov 2023 23:27:18.081 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
438:M 21 Nov 2023 23:27:18.099 * Ready to accept connections
Hit:1 http://deb.debian.org/debian bookworm InRelease
Get:2 http://deb.debian.org/debian bookworm-updates InRelease [52.1 kB]
Hit:3 http://deb.debian.org/debian-security bookworm-security InRelease
Fetched 52.1 kB in 1s (57.2 kB/s)
Reading package lists...
Package tesseract-ocr-eng already installed!
Package tesseract-ocr-fra already installed!
Package tesseract-ocr-ger not found! :(
Mapping UID and GID for paperless:paperless to 0:0
Creating directory /config/media/documents
Creating directory /config/media/documents/originals
Creating directory /config/media/documents/thumbnails
Creating directory /tmp/paperless
Adjusting permissions of paperless files. This may take a while.
Waiting for Redis...
Connected to Redis broker.
Apply database migrations...
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, django_celery_results, documents, guardian, paperless_mail, sessions
Running migrations:
  No migrations to apply.
Running Django checks
SystemCheckError: System check identified some issues:

ERRORS:
?: OCR output mode ""skip"" is not valid

System check identified 1 issue (0 silenced).
```

**Comment by alexbelgium** [comment]
Ah, I see... I need to sanitize the arguments to avoid putting "" if there is already some

**Comment by alexbelgium** [comment]
Hopefully solved in `2.0.0.1-5test3`

**Comment by alexbelgium** [comment]
Actually, probably `2.0.0.1-5test4` as it induced new issues. Now I'm putting "" only if there is a blank in the variable (initial source of this code modification)

**Comment by undauntedjogging** [comment]
I have the same issue:
My Paperless is not starting anymore 

 **Add-on version: 2.0.0.1-5test
 You are running the latest version of this add-on.**


Running migrations:
  No migrations to apply.
Running Django checks
SystemCheckError: System check identified some issues:
ERRORS:
?: OCR output mode ""skip"" is not valid
System check identified 1 issue (0 silenced).

**Comment by undauntedjogging** [comment]
How can i rollback now?

**Comment by alexbelgium** [comment]
Hi, I've pushed a new version just now that should solve this issue, just testing now

**Comment by undauntedjogging** [comment]
All my configurations are gone, all my files / documents are also gone after updating to this new verson.

What happened here?

**Comment by alexbelgium** [comment]
Hi, well nearly working but again an issue I need to solved :
```
Package tesseract-ocr-'eng not found! :(
Package tesseract-ocr-fra already installed!
Package tesseract-ocr-ger' not found! :(
```

**Comment by alexbelgium** [comment]
> All my configurations are gone, all my files / documents are also gone after updating to this new verson.
> 
> What happened here?

What do you mean?

According to change log, I had to adapt to the new way of working of HA : all the files were migrated from the /config folder of HA (that will not be supported in the future) to the new config system of HA (https://github.com/alexbelgium/hassio-addons/blob/master/paperless_ngx/CHANGELOG.md#200b1-5-20-11-2023). To access it, you need another addon such as filebrowser and find your data in /addons_config/something-paperless-ngx. Everything will have migrated automatically

If your files are not in the paperless UI anymore, that's a different issue and I would need a full log including the paths you have set for your data directory. Also, which version have you updated from ?

**Comment by cnru** [comment]
Did not change yet also with version 2.0.0.1-5test2 still getting the same error

**Comment by cnru** [comment]
Oki wait until I can update... Is not shown yet

**Comment by alexbelgium** [comment]
Either you need to wait a couple hours or go in the same place you added my custom repo and click on "look for updates"

**Comment by cnru** [comment]
Fix is working - Thanks for fast response.

By the way is the Database now been backed up on a Home Assistant Backup run?

**Comment by alexbelgium** [comment]
So the very good news is that as the new config system is used, the database should now be backed directly in the addon backup !

And therefore restoring the backup of the addon will also restore the database, which was not previously the case as the database was stored in the middle of the HA configuration files
