### ISSUE TITLE
🐛 [birdnet-pi] birds.db not written/used

### ISSUE THREAD

**Issue by frostworx** [alexbelgium/hassio-addons#1369]
### Description

Hello,
foremost, thank you very much for adding birdnet-pi to your amazing addon-collection!
I immediately tried it after [you announced it](https://github.com/mcguirepr89/BirdNET-Pi/issues/211#issuecomment-2081183546) a few days ago, and it worked excellent out of the box.

I did not test every change you made _(wow, you have been very busy!)_ since, as I was sick, but at least since the last changes, the `birds.db` used is no longer written. The BirdSong folder defined in the addon settings is unused as well, which possibly is the core problem _(see reproduction steps below)_

It might worth to mention that I use a rtsp camera stream as an audio source _(it seems to work fine though)_

### Reproduction steps

```bash
1. _(remove the addon and the config files completely)_ install the addon
2. _(select an alternative port, as port 80 is already in use)_
3. _(set TZ Europe/Berlin)_
4. start the addon
5. open the webinterface 
   - using ingress via nabu casa the "Tools" menu can't be opened _(tiny checkbox which toggles between 'legacy view' and 'normal view' text when clicking without any obvious effect)_
   - using the local ip the "Tools" menu can be opened
6. goto Tools->Settings
7. change Latitude+Longitude, active ntp checkbox, set the timezone again -> Update Settings
8. under "Advanced Settings" add the rtsp audio stream, set a birdpi password -> Update Settings
9. _(restarting here doesn't help)_
10. when entering the container, you can see that
    - wav files are processed under /home/pi/BirdSongs/StreamData/
    - the /config/BirdSongs/ directory remains empty _(besides the auto created subdirectories 'By_Date' and 'Charts')_

11. when killing the '/usr/bin/sudo -u pi /home/pi/BirdNET-Pi/birdnet/bin/python3 /usr/local/bin/birdnet_analysis.py' process and running it manually, the live log shows that birds are actively detected. The main problem possibly is this repeating permission denied error:

[birdnet_analysis][ERROR] Unexpected error: 
Traceback (most recent call last):
  File "/usr/local/bin/birdnet_analysis.py", line 114, in handle_reporting_queue
    detection.file_name_extr = extract_detection(file, detection)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/BirdNET-Pi/scripts/utils/reporting.py", line 74, in extract_detection
    os.makedirs(new_dir, exist_ok=True)
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/home/pi/BirdSongs/Extracted/By_Date/2024-05-01'
[birdnet_analysis][INFO] Analyzing /home/pi/BirdSongs/StreamData/2024-05-01-birdnet-RTSP_1-16:51:11.wav

and indeed: it is not possible to create the date subdirectory manually as pi user.
creating the dir as root, chowning it to pi:pi (and even chmod 777 on it doesn't have any effect on the permission denied problem though)

I would appreciate it if you could help. Please let me know if you need any further information.

Not sure if it is related:

the /usr/share/hassio/addon_configs/db21ed7f_birdnet-pi on the host side belongs to my main user (who is also running pulse audio via xfce on the host), where other addon directories like db21ed7f_filebrowser belong to root.

I'm running home assistant on an Arch Linux on bare metal BTW ;)
```

### Addon Logs

```bash
[server][INFO] READING AUDIO DATA...
[server][INFO] READING DONE! READ 5 CHUNKS.
[server][INFO] ANALYZING AUDIO...
[server][INFO] DONE! Time 0.34 SECONDS
[server][INFO] 0.0;3.0-('Passer domesticus_Haussperling', 0.6378058)
[server][INFO] 3.0;6.0-('Passer domesticus_Haussperling', 0.8998311)
[server][INFO] 6.0;9.0-('Myiarchus cinerascens_Kalifornienschopftyrann', 0.059039034)
[server][INFO] 9.0;12.0-('Passer domesticus_Haussperling', 0.25815734)
[server][INFO] 12.0;15.0-('Passer domesticus_Haussperling', 0.7686956)
[birdnet_analysis][INFO] Analyzing /home/pi/BirdSongs/StreamData/2024-05-01-birdnet-RTSP_1-16:44:03.wav
[server][INFO] READING AUDIO DATA...
[birdnet_analysis][ERROR] Unexpected error: 
Traceback (most recent call last):
  File "/usr/local/bin/birdnet_analysis.py", line 114, in handle_reporting_queue
    detection.file_name_extr = extract_detection(file, detection)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/BirdNET-Pi/scripts/utils/reporting.py", line 74, in extract_detection
    os.makedirs(new_dir, exist_ok=True)
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/home/pi/BirdSongs/Extracted/By_Date/2024-05-01'
[server][INFO] READING DONE! READ 5 CHUNKS.
[server][INFO] ANALYZING AUDIO...
```

### Architecture

amd64

**Comment by alexbelgium** [comment]
Hi ! Indeed I thought it was working but each day I'm discovering new improvements or issues :-)
I'm quite happy with the latest (-15) version, I'm just now redirecting logs to the container

This software is so great this is incredible and I just can't stop tweaking it for the moment :-)

What is not fully working now : 
- Service logs (but I've found the solution and it will work in -16
- Some things in ingress ; but webui fully works in direct access
- View logs page (but perhaps not useful as the logs can be seen in container logs ; I'll have to see if I can redirect it to /proc/1/fd/1)

Regarding your issue, it seems it boils down to "[Errno 13] Permission denied: '/home/pi/BirdSongs/Extracted/By_Date/2024-05-01'"

I'll check a quick fix

**Comment by alexbelgium** [comment]
Mmh I read your message a bit too quickly and see you already tested several things.

Which version are you running ; could you please update to v-15 which just finished building ?
Also, could you please check if there is any error in the addon startup log ?

In particular, it should check already check for permission when starting ? Thanks !

https://github.com/alexbelgium/hassio-addons/blob/3bc468b709c3215f5977a9c21661558d025e243a/birdnet-pi/rootfs/etc/cont-init.d/01-structure.sh#L21-L32

**Comment by alexbelgium** [comment]
I've just thought that it might be that the addon uses /tmp mounted as a tmpfs by HomeAssistant OS, but perhaps it is not available if you have a supervised installation... I've corrected the code to first check if it is a tmpfs before trying to use it ; and remove all hardcoded references to instead use the "normal" folder. I'm using the same strategy as BirdNET-Pi : using symlinks betwen the actual folders and the ones that are expected and globally hardcoded in the initial scripts (such as /home/pi/BirdSongs/Streamdata)

**Comment by frostworx** [comment]
Wow, you're fast! Thank you so much for all your work!

I fully agree the software is fantastic _(an www.inaturalist.org integration would be a great addition, but on the other hand one, including me  might not like that the long/lat are at a fixed position and therefore would tell where the uploader lives exactly :))_


I just updated to `-16` _(sorry for not having mentioned the version before - it was on `-13`)_ and could not see any errors in the logs _(didn't see  01-structure.sh being mentioned though)_

I tried to start the script manually, but could not find it in the container _(`/etc/cont-init.d/` is empty and a recursive find didn't find it as well)_
here is a merged log of two start attempts, I hope it helps:

```
Starting...
/etc/cont-init.d/00-banner.sh: executing

-----------------------------------------------------------
 Add-on: BirdNET-pi
 realtime acoustic bird classification system
-----------------------------------------------------------
 Add-on version: 0.13-16
 You are running the latest version of this add-on.
 System: Arch Linux  (amd64 / qemux86-64)
 Home Assistant Core: 2024.4.4
 Home Assistant Supervisor: 2024.04.4
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
-----------------------------------------------------------
 Provided by: https://github.com/alexbelgium/hassio-addons 
-----------------------------------------------------------
/etc/cont-init.d/00-global_var.sh: executing
BIRDSONGS_FOLDER='/config/BirdSongs'
BIRDS_ONLINE_INFO='ebird.org'
TZ='Europe/Berlin'
pi_password='pass'
/etc/cont-init.d/00-local_mounts.sh: executing
/etc/cont-init.d/00-smb_mounts.sh: executing
/etc/cont-init.d/01-config_yaml.sh: executing
Setting permissions for the config.yaml directory

Load environment variables from /config/config.yaml if existing
If accessing the file with filebrowser it should be mapped to /addon_configs/db21ed7f-birdnet-pi/config.yaml
---------------------------------------------------------

Wiki here on how to use : github.com/alexbelgium/hassio-addons/wiki/Add‐ons-feature-:-add-env-variables
... no env variables found, exiting
/etc/cont-init.d/01-custom_script.sh: executing
Execute /addon_configs/db21ed7f-birdnet-pi/birdnet-pi.sh if existing
Wiki here : github.com/alexbelgium/hassio-addons/wiki/Add-ons-feature-:-customisation
/etc/cont-init.d/32-nginx_ingress.sh: executing
Adapting for ingress
/etc/cont-init.d/99-run.sh: executing
 
[17:27:58] INFO: Ensuring the file structure is correct :
... creating default files
... BIRDSONGS_FOLDER set to /config/BirdSongs
... creating default folders ; it is highly recommended to store those on a ssd
... setting StreamData and Processed on tmpfs to reduce disk wear
... set permissions to user pi
... creating symlink for birdnet.conf
... creating symlink for birds.db
... creating symlink for apprise.txt
... creating symlink for exclude_species_list.txt
... creating symlink for include_species_list.txt
... creating symlink for IdentifiedSoFar.txt
... creating symlink for /config/BirdSongs/Extracted/By_Date
... creating symlink for /config/BirdSongs/Extracted/Charts
 
[17:27:58] INFO: Starting system services
... setting timezone to Europe/Berlin
... correcting systemctl
... starting dbus
Starting system message bus: dbus.

[17:27:58] INFO: Starting BirdNET-Pi services
+ my_dir=/home/pi/BirdNET-Pi/scripts
+ sudo systemctl stop birdnet_recording.service
+ services=(chart_viewer.service spectrogram_viewer.service icecast2.service birdnet_recording.service birdnet_analysis.service birdnet_log.service birdnet_stats.service)
+ for i in "${services[@]}"
+ sudo systemctl restart chart_viewer.service
+ for i in "${services[@]}"
+ sudo systemctl restart spectrogram_viewer.service
for i in "${services[@]}"
+ sudo systemctl restart birdnet_recording.service
+ for i in "${services[@]}"
+ sudo systemctl restart birdnet_analysis.service
+ for i in "${services[@]}"
+ sudo systemctl restart birdnet_log.service
+ for i in "${services[@]}"
+ sudo systemctl restart birdnet_stats.service
+ for i in {1..5}
+ systemctl is-active --quiet birdnet_analysis.service
+ logger '[/./home/pi/BirdNET-Pi/scripts/restart_services.sh] birdnet_analysis.service is running'
+ break
 
[17:28:10] INFO: Adapting webui
... adapting labels according to birdnet.conf file to de
Archive:  /home/pi/BirdNET-Pi/model/labels_nm.zip
  inflating: /home/pi/BirdNET-Pi/model/labels_de.txt  
Archive:  /home/pi/BirdNET-Pi/model/labels_nm.zip
  inflating: /home/pi/BirdNET-Pi/model/labels_en.txt  
... removing System Controls from webui as should be used from HA
... using gotty-x86_64 in phpsysinfo
[17:28:10] INFO: Starting upstream container
 
Starting the upstream container
 
[custom-init] Service files found in /custom-services.d
[custom-init] 00-php_pfm: service detected, copying...
[custom-init] 00-php_pfm: copied
[custom-init] 01-avahi: service detected, copying...
[custom-init] 01-avahi: copied
[custom-init] 02-caddy: service detected, copying...
[custom-init] 02-caddy: copied
[custom-init] 02-nginx.sh: service detected, copying...
[custom-init] 02-nginx.sh: copied
[custom-init] 03-throttlerecording: service detected, copying...
[custom-init] 03-throttlerecording: copied
[migrations] started
[migrations] no migrations found
───────────────────────────────────────
  _____ __ __ _____ _____ _____ _____ 
 |     |  |  |   __|_   _|     |     |
 |   --|  |  |__   | | | |  |  | | | |
 |_____|_____|_____| |_| |_____|_|_|_|
       _____ __ __ _ __    ____  
      | __  |  |  | |  |  |    \ 
      | __ -|  |  | |  |__|  |  |
      |_____|_____|_|_____|____/ 

  Based on images from linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    0
User GID:    0
───────────────────────────────────────

[custom-init] No custom files found, skipping...
Starting service: php pfm
Starting service: throttlerecording
Starting service: nginx
Starting service: avahi daemon
```

**Comment by frostworx** [comment]
Oh, just have seen your comment before. I'm testing just right now :)

**Comment by frostworx** [comment]
I'm sorry having to tell you , that the 
`PermissionError: [Errno 13] Permission denied: '/home/pi/BirdSongs/Extracted/By_Date/2024-05-01'`
problem remains with `v17`

I'm trying to find out something useful, please let me know when I can help.

**Comment by alexbelgium** [comment]
Thanks! It's strange that the log show 99-run.sh executing as I had renamed it to 91-run.sh... https://github.com/alexbelgium/hassio-addons/tree/master/birdnet-pi/rootfs/etc/cont-init.d... And my startup routine deletes the script's after execution which explains their absence :) 

Could you please fully delete the addon ; refresh the repo ; and reinstall v17? I hope it will pull the right image that shows the run script as 91-run

Thanks very much for being my beta tester :) It works on my HAos rpi 4 but I guess some adaptations are needed for HA supervised

**Comment by frostworx** [comment]
I'm glad I can help :)

Just tested after removing the addon and reinstalling completely, but kept the 
`addon_configs/db21ed7f_birdnet-pi/` and got this log:

```
[migrations] started
[migrations] no migrations found

  You can now view your Streamlit app in your browser.

  URL: http://localhost:8501/stats

───────────────────────────────────────
  _____ __ __ _____ _____ _____ _____ 
 |     |  |  |   __|_   _|     |     |
 |   --|  |  |__   | | | |  |  | | | |
 |_____|_____|_____| |_| |_____|_|_|_|
       _____ __ __ _ __    ____  
      | __  |  |  | |  |  |    \ 
      | __ -|  |  | |  |__|  |  |
      |_____|_____|_|_____|____/ 

  Based on images from linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    0
User GID:    0
───────────────────────────────────────

[custom-init] No custom files found, skipping...
Starting service: php pfm
Starting service: throttlerecording
Starting service: nginx
Starting service: avahi daemon
Found user 'avahi' (UID 104) and group 'avahi' (GID 106).
Successfully dropped root privileges.
avahi-daemon 0.8 starting up.
Loading service file /etc/avahi/services/http.service.
socket() failed: Address family not supported by protocol
Failed to create IPv6 socket, proceeding in IPv4 only mode
socket() failed: Address family not supported by protocol
Joining mDNS multicast group on interface eth0.IPv4 with address 172.30.33.3.
New relevant interface eth0.IPv4 for mDNS.
Joining mDNS multicast group on interface lo.IPv4 with address 127.0.0.1.
New relevant interface lo.IPv4 for mDNS.
Network interface enumeration completed.
Registering new address record for 172.30.33.3 on eth0.IPv4.
Registering new address record for 127.0.0.1 on lo.IPv4.
[ls.io-init] done.
Server startup complete. Host name is db21ed7f-birdnet-pi.local. Local service cookie is 4000435584.
Starting service: caddy
{"level":"info","ts":1714580195.7175438,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":""}
{"level":"warn","ts":1714580195.719113,"msg":"Caddyfile input is not formatted; run 'caddy fmt --overwrite' to fix inconsistencies","adapter":"caddyfile","file":"/etc/caddy/Caddyfile","line":1}
{"level":"info","ts":1714580195.720031,"logger":"admin","msg":"admin endpoint started","address":"localhost:2019","enforce_origin":false,"origins":["//127.0.0.1:2019","//localhost:2019","//[::1]:2019"]}
{"level":"info","ts":1714580195.7202754,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc00059fa00"}
{"level":"warn","ts":1714580195.7202926,"logger":"http.auto_https","msg":"server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server","server_name":"srv0","http_port":80}
{"level":"warn","ts":1714580195.7210364,"logger":"tls","msg":"unable to get instance ID; storage clean stamps will be incomplete","error":"open /home/pi/.local/share/caddy/instance.uuid: no such file or directory"}
{"level":"info","ts":1714580195.7253904,"logger":"http.log","msg":"server running","name":"srv0","protocols":["h1","h2","h3"]}
{"level":"info","ts":1714580195.729334,"msg":"autosaved config (load with --resume flag)","file":"/home/pi/.config/caddy/autosave.json"}
{"level":"info","ts":1714580195.7293637,"msg":"serving initial configuration"}
{"level":"info","ts":1714580195.730753,"logger":"tls","msg":"cleaning storage unit","storage":"FileStorage:/home/pi/.local/share/caddy"}
{"level":"info","ts":1714580195.731045,"logger":"tls","msg":"finished cleaning storage units"}
Service "BirdNET-Pi db21ed7f-birdnet-pi" (/etc/avahi/services/http.service) successfully established.
[birdnet_analysis][INFO] Analyzing /home/pi/BirdSongs/StreamData/2024-05-01-birdnet-RTSP_1-18:16:30.wav
[server][INFO] READING AUDIO DATA...
[rtsp @ 0x60b33d848a40] method SETUP failed: 461 Unsupported transport
[h264 @ 0x60b33d84d4c0] Missing reference picture, default is 0
[h264 @ 0x60b33d84d4c0] decode_slice_header error
[server][INFO] READING DONE! READ 5 CHUNKS.
[server][INFO] ANALYZING AUDIO...
[server][INFO] loaded META model
[server][INFO] DONE! Time 0.47 SECONDS
[server][INFO] 0.0;3.0-('Buteo buteo_Mäusebussard', 0.7614916)
[server][INFO] 3.0;6.0-('Turdus merula_Amsel', 0.34317088)
[server][INFO] 6.0;9.0-('Chloris chloris_Grünfink', 0.6767236)
[server][INFO] 9.0;12.0-('Turdus merula_Amsel', 0.25335354)
[server][INFO] 12.0;15.0-('Turdus merula_Amsel', 0.6934279)
[birdnet_analysis][ERROR] Unexpected error: 
Traceback (most recent call last):
  File "/usr/local/bin/birdnet_analysis.py", line 114, in handle_reporting_queue
    detection.file_name_extr = extract_detection(file, detection)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/BirdNET-Pi/scripts/utils/reporting.py", line 74, in extract_detection
    os.makedirs(new_dir, exist_ok=True)
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 225, in makedirs
  PermissionError: [Errno 13] Permission denied: '/home/pi/BirdSongs/Extracted/By_Date/2024-05-01'
```

mhh, I'm sure I've seen `91-run.sh` before copying, maybe it left the buffer.
I'll retry with a clean addon config :)

**Comment by frostworx** [comment]
Hmm, I'm a bit confused now.
I removed all config files (the whole `/usr/share/hassio/addon_configs/db21ed7f_birdnet-pi/ `dir)
and started the addon without configuring anything other  than the options available in the home assistant addon settings
it is using `91-run.sh`, so far so good, but for whatever reason it still seems to detect birds (rtsp camera stream is not configured). The detected birds are not added though, as the 
`PermissionError: [Errno 13] Permission denied: '/home/pi/BirdSongs/Extracted/By_Date/2024-05-01'`
error persists
Maybe I have some leftovers lying around from previous installations - *looking around* :)

**Comment by frostworx** [comment]
hm, maybe I got something.
I tried another reinstall _(back at your git master `-15`)_ with a clean config.
logs looked unsuspicious again, but I recognized inside the container that a 
directory
`/home/pi/BirdSongs/May-2024/01-Wednesday/`
was created.
That directory is not created in the shared /config/BirdSongs dir, any chance a volume mount or symlink is missing here?

**Comment by frostworx** [comment]
`01-structure.sh`

contains

`chown -R pi:pi "$BIRDSONGS_FOLDER_OPTION"`

the defined var is 

`BIRDSONGS_FOLDER`
though.

**Comment by frostworx** [comment]
I played a bit with a copy of `/etc/cont-init.d/01-structure.sh`
within the container.
haven't debugged too deep, but something is broken with the

` /home/pi/BirdSongs/Extracted/By_Date/`
symlink

When touching a dummy file in `/config/BirdSongs/Extracted/By_Date/dummy` on the host side
that file is not visible from the container side _(all files in `/config/*` behave correctly though)_
Instead I see a `/config/BirdSongs/By_Date/2024-05-01/` directory on the container side,
which does not exist on the host side.

after a manual
`root@db21ed7f-birdnet-pi:/media/bird/etc/cont-init.d# rm -r /home/pi/BirdSongs/Extracted/By_Date`

I was able to temporarily see analyzed bird wavs:

```
root@db21ed7f-birdnet-pi:/media/bird/etc/cont-init.d# ls -la /home/pi/BirdSongs/Extracted/By_Date/2024-05-01/Mönchsgrasmücke/Mönchsgrasmücke-
Mönchsgrasmücke-70-2024-05-01-birdnet-RTSP_1-19:48:26.mp3      Mönchsgrasmücke-71-2024-05-01-birdnet-RTSP_1-19:48:57.mp3      Mönchsgrasmücke-75-2024-05-01-birdnet-RTSP_1-19:47:56.mp3.png  Mönchsgrasmücke-88-2024-05-01-birdnet-RTSP_1-19:55:34.mp3.png
Mönchsgrasmücke-70-2024-05-01-birdnet-RTSP_1-19:48:26.mp3.png  Mönchsgrasmücke-71-2024-05-01-birdnet-RTSP_1-19:48:57.mp3.png  Mönchsgrasmücke-78-2024-05-01-birdnet-RTSP_1-19:48:41.mp3      Mönchsgrasmücke-94-2024-05-01-birdnet-RTSP_1-19:48:26.mp3
Mönchsgrasmücke-70-2024-05-01-birdnet-RTSP_1-19:49:12.mp3      Mönchsgrasmücke-72-2024-05-01-birdnet-RTSP_1-19:56:19.mp3      Mönchsgrasmücke-78-2024-05-01-birdnet-RTSP_1-19:48:41.mp3.png  Mönchsgrasmücke-94-2024-05-01-birdnet-RTSP_1-19:48:26.mp3.png
Mönchsgrasmücke-70-2024-05-01-birdnet-RTSP_1-19:49:12.mp3.png  Mönchsgrasmücke-75-2024-05-01-birdnet-RTSP_1-19:47:56.mp3      Mönchsgrasmücke-88-2024-05-01-birdnet-RTSP_1-19:55:34.mp3      
root@db21ed7f-birdnet-pi:/media/bird/etc/cont-init.d# ls -la /home/pi/BirdSongs/Extracted/ate/2024-05-01/ 
Amsel/             Gartenrotschwanz/  Hausrotschwanz/    Krickente/         Mönchsgrasmücke/ 
```

those disappeared shortly after and werer added to the birds.db :)

This is reproducable.

`rm -r /home/pi/BirdSongs/Extracted/By_Date`

followed by a manual

`/usr/bin/sudo -u pi /home/pi/BirdNET-Pi/birdnet/bin/python3 /usr/local/bin/birdnet_analysis.py`

works to a working process.

**Comment by alexbelgium** [comment]
Thanks! I had corrected the systemctl services birndet_analysis to use `/usr/bin/sudo -u pi` in the command, as you did, instead of relying on the USER field of the service. It seems to me that the custom systemctl file needed to execute it on a container (which is normally not possible) has a bug with services ownership. So normally your manual command should be the default one

Regarding the symlink, the default behavior should be that `$HOME/BirdNET-Pi/BirdSongs/Extracted/By_Date` is mapped to `/config/By_Date` ; which should be done with this line for which I don't see anything wrong at first glance :
https://github.com/alexbelgium/hassio-addons/blob/a359b99ab291b29cc8c65f6968d88a5db184351e/birdnet-pi/rootfs/etc/cont-init.d/01-structure.sh#L68-L72

In theory it should do exactly what you describe (where folders is By_Chart) : 
- rm -r "$HOME/BirdSongs/Extracted/${folders:?}"
- sudo -u pi ln -fs "$BIRDSONGS_FOLDER"/"$folders" "$HOME/BirdSongs/Extracted/$folders"

I wonder if we should do the symlink with root and sudo afterwards instead ? Or perhaps it is a permissions difference ?

Btw the easiest to test such type of codes if by using the file named /config/birdnet-pi.sh : it is executed at each boot and allows to check if the code helps in a repeatable way. Here is a bit more info : https://github.com/alexbelgium/hassio-addons/wiki/Add%E2%80%90ons-feature-:-customisation

For example you could add in this file : 
```
#!/bin/bash
echo "remove folder after symlink"
echo "rm -r /home/pi/BirdSongs/Extracted/By_Date" >> /etc/cont-init.d/01-structure.sh
```

Btw, I've compiled a list of my observations so far & bugs (both in BirdNET-Pi and the addon) : https://github.com/alexbelgium/hassio-addons/issues/1371

**Comment by frostworx** [comment]
yeah, sorry for the confusion. Indeed I picked both rm & symlink commands from `01-structure.sh` and got it working again after some quick testing.

I'll try to look deeper into it soonish and report back any findings.

 _(quick guess: any chance we have a shell with limited variables when it is running automatically in the container and therefore '$HOME' is not defined in [this](https://github.com/alexbelgium/hassio-addons/blob/a359b99ab291b29cc8c65f6968d88a5db184351e/birdnet-pi/rootfs/etc/cont-init.d/01-structure.sh#L71) sudo line?)_

Thanks for all the efforts!

**Comment by frostworx** [comment]
quick find, within the container:

as root:

```
root@db21ed7f-birdnet-pi:/# ls -la /config/BirdSongs
total 16
drw-rw-r-- 4 pi pi 4096 May  2 07:48 .
drwxrwxrwx 3 pi pi 4096 May  2 16:32 ..
drw-rw-r-- 2 pi pi 4096 May  2 07:48 By_Date
drw-rw-r-- 2 pi pi 4096 May  2 07:48 Charts
```

as pi user:

```
pi@db21ed7f-birdnet-pi:/config$ cd /
pi@db21ed7f-birdnet-pi:/$ ls -la  /config/BirdSongs
ls: cannot access '/config/BirdSongs/..': Permission denied
ls: cannot access '/config/BirdSongs/By_Date': Permission denied
ls: cannot access '/config/BirdSongs/.': Permission denied
ls: cannot access '/config/BirdSongs/Charts': Permission denied
total 0
d????????? ? ? ? ?            ? .
d????????? ? ? ? ?            ? ..
d????????? ? ? ? ?            ? By_Date
d????????? ? ? ? ?            ? Charts
```
doesn't look too sane :)

**Comment by frostworx** [comment]
a dirty 
`chmod  777 /config/BirdSongs` _(as root)_

fixes the issue for the pi user:

```
ls -la /config/BirdSongs
total 16
drwxrwxrwx 4 pi pi 4096 May  2 07:48 .
drwxrwxrwx 3 pi pi 4096 May  2 16:32 ..
drw-rw-r-- 2 pi pi 4096 May  2 07:48 By_Date
drw-rw-r-- 2 pi pi 4096 May  2 07:48 Charts
```

**Comment by frostworx** [comment]
sorry for the noise...

a dirty recursive 

`chmod -R 777 /config/BirdSongs`

fixes the core permission denied problem

**Comment by frostworx** [comment]
yes, I can confirm that

1) starting from from scratch
2) enter the container
3) `chmod -R 777 /config/BirdSongs`
4) `/usr/bin/sudo -u pi /home/pi/BirdNET-Pi/birdnet/bin/python3 /usr/local/bin/birdnet_analysis.py`

works as expected.

using birdnet-pi.sh for the workaround doesn't work, because `/config/BirdSongs` is not ready yet when it is executed:

```
etc/cont-init.d/01-custom_script.sh: executing
Execute /addon_configs/db21ed7f-birdnet-pi/birdnet-pi.sh if existing
Wiki here : github.com/alexbelgium/hassio-addons/wiki/Add-ons-feature-:-customisation
... script found, executing
DBG before chmod:
ls: cannot access '/config/BirdSongs': No such file or directory
Error : /etc/cont-init.d/01-custom_script.sh exiting 2
/etc/cont-init.d/01-structure.sh: executing
```

**Comment by alexbelgium** [comment]
Thanks very much for your tests !

I am not a perfect expert but I wonder if this is because I put permissions at 644. Perhaps I should try 755 instead. I wonder also if this is because UID 1000 is non-exclusive to pi.

I tried with portainer on my own system but from `pi` user I see the correct permissions...

Btw, usually I use then the birdnet-pi.sh to modify other files, such as adding in it a `echo "chmod -R 777 /config/BirdSongs" >> /etc/cont-init.d/*run*` ;-)

But it's great you've found a solution, thanks!!

**Comment by alexbelgium** [comment]
that's what I meant perhaps in a more obscure way ;-)

To make sure other scripts have run before I execute custom commands, I use birdnet-pi.sh to modify a script that has run at the right moment. For example, using echo in birdnet-pi.sh to add the chmod command after the folder was created by doing `echo "chmod -R 777 /config/BirdSongs" >> /etc/cont-init.d/*run*`

Btw I'm embarassed to say that I had forgotten to chmod the "$BIRDSONGS_FOLDER", so I've added that and will reference the commit just below - I've always changed the default chmod to 755 in case it helps

**Comment by alexbelgium** [comment]
> glad I could help :)
> 
> Likely you read to quickly :) I [wanted to use](https://github.com/alexbelgium/hassio-addons/issues/1369#issuecomment-2090792159) `birdnet-pi.sh`, but `/config/BirdSongs` is not ready when it is executed.
> 
> _btw: I registered on buymeacoffee earlier today, just to rage-quit minutes later, after recognizing they do not have a paypal option. Any chance you can add a paypal donation button to your project? :)_

really they don't support paypal??? quite stupid from their part when I initially registered I thought it did... especially as my own paypal account is connected as a receiver!! I'll think about the paypal button, good idea :-) I don't really need the money but it is always nice to feel appreciated ;-)

**Comment by frostworx** [comment]
> > glad I could help :)
> > Likely you read to quickly :) I [wanted to use](https://github.com/alexbelgium/hassio-addons/issues/1369#issuecomment-2090792159) `birdnet-pi.sh`, but `/config/BirdSongs` is not ready when it is executed.
> > _btw: I registered on buymeacoffee earlier today, just to rage-quit minutes later, after recognizing they do not have a paypal option. Any chance you can add a paypal donation button to your project? :)_
> 
> really they don't support paypal??? quite stupid from their part when I initially registered I thought it did... especially as my own paypal account is connected as a receiver!! I'll think about the paypal button, good idea :-) I don't really need the money but it is always nice to feel appreciated ;-)

unfortunately no:

https://buymeacoffee.com/kingdomkeys/paypal-longer-supported-buy-me-coffee?l=de

I very much appreciate your might excellent addon collection :)

**Comment by frostworx** [comment]
> that's what I meant perhaps in a more obscure way ;-)
> 
> To make sure other scripts have run before I execute custom commands, I use birdnet-pi.sh to modify a script that has run at the right moment. For example, using echo in birdnet-pi.sh to add the chmod command after the folder was created by doing `echo "chmod -R 777 /config/BirdSongs" >> /etc/cont-init.d/*run*`
> 
> Btw I'm embarassed to say that I had forgotten to chmod the "$BIRDSONGS_FOLDER", so I've added that and will reference the commit just below - I've always changed the default chmod to 755 in case it helps

hehe, looks like I read too quickly - sorry for the noise.
Thanks a lot for the fix :)

_(yay, I already have 130 birds/7 species in my db since today - birdnetpi is wonderful :))_

**Comment by frostworx** [comment]
`0.13-18` up&running and I can confirm that it does work now!

**Thank you very much!!!**

*closing here*

**Comment by alexbelgium** [comment]
That's great thanks very much! For the help, the feedback and the kind words ;) I also took the opportunity to set a PayPal link on my main readme indeed it is a convenient proxy that could could interest other people 

Btw I'm still trying different settings watchout that it seems better to lower the species threshold and exclude false positive species if you want to detect many slight less common birds, including owls. Have fun!

**Comment by frostworx** [comment]
yay great! I can confirm the paypal button works :)
Can't wait to see if we have owls around. thank you so much! :)
Have fun as well!

**Comment by alexbelgium** [comment]
Thanks very much!!

**Comment by alexbelgium** [comment]
Thanks very much!!

BTW have you tested the feature that birdnet pi can send a text message with a Flickr picture of the latest identified birds? Just discovered it and it is great!
