### ISSUE TITLE
✨ [REQUEST] Navidrome

### ISSUE THREAD

**Issue by baldarn** [alexbelgium/hassio-addons#1409]
### Checked

- [X] If a new addon, I have checked on  Google that such as addon doesn't already exists
- [X] If a new feature, I have searched in the discussions & issues that it was not already covered

### Which addon?

Navidrome
https://github.com/navidrome/navidrome/

### Is your feature request related to a problem? Please describe

just want to add this

someone tried to use that, but with no luck

https://github.com/navidrome/navidrome/issues/2605

### Describe the solution you'd like

add the addon

**Comment by baldarn** [comment]
will try to take care of it

**Comment by baldarn** [comment]
@alexbelgium same problem with the image for `navidrome`... i fell unlucky ;(

**Comment by alexbelgium** [comment]
> @alexbelgium same problem with the image for `navidrome`... i fell unlucky ;(

What problem do you mean?

**Comment by baldarn** [comment]
the image is not present
![Screenshot_20240522_164920](https://github.com/alexbelgium/hassio-addons/assets/2814802/ad1246a6-88f2-4a8f-bdeb-67c7ba5a0e44)

**Comment by alexbelgium** [comment]
mmh I'll push it

**Comment by hiagocosta** [comment]
I have a question about navidrome...
is it possible that I can change music folder to a SMB NAS, just like we can make with other addons?

**Comment by alexbelgium** [comment]
Added :)

**Comment by alexbelgium** [comment]
Mmh indeed the image doesn't build but I can't understand what is wrong. Are the files formatted with lf and not crlf?

**Comment by bilogic** [comment]
Navidrome works if it is loaded standalone, it does not work if we try to load in HA's iframe (ingress).

To keep it simple, if we can set `ND_BASEURL` to `.`, that should fix it, currently navidrom panics.

**Comment by hiagocosta** [comment]
I have to add ND_BASEURL as a variable?

**Comment by bilogic** [comment]
> I have to add ND_BASEURL as a variable?

Yes, but that is still not going to make things work. See https://github.com/navidrome/navidrome/issues/2605

**Comment by hiagocosta** [comment]
i'm still unable to run this addon, any plans to update?
it keeps start and return back

**Comment by baldarn** [comment]
hi @hiagocosta , will try to fix this next week

**Comment by alexbelgium** [comment]
> hi @hiagocosta , will try to fix this next week

Thanks! Sorry I don't have much time to look for the moment but don't hesitate if you need any support for specific elements

**Comment by alexbelgium** [comment]
Argh indeed it seems automerge doesn't work but I don't understand why... I'll have a look!

If you want I'll try to look at the code tomorrow to see if I can find something :)

**Comment by alexbelgium** [comment]
Are you on HA community? They accept PM and we can exchange details there

**Comment by celynw** [comment]
I have an [addons repository with Navidrome](https://github.com/celynw/ha-addons/tree/master/navidrome), in case it's of any help.

I did base most of it on @alexbelgium's amazing work, after all

**Comment by alexbelgium** [comment]
Hi celynw, very nice work! Glad to see that what I did can be useful to others also - the community lives on inspiring ourselves from other's work and taking it further! At my start, most of my repo was inspired by https://github.com/petersendev/hassio-addons ;-)

The failed run is due to an automerge workflow that is not working ;-) long story short I wanted to find a way for "external" users to trigger a build so they could "host" their addons on my repo but still be fully autonomous in coding & building. As such, in theory the `\automerge` tag should trigger an automatic merge of the PR on which it is written as a comment. However, the workflow stopped working and is now sending failed runs to everyone until I have time to correct that ;-)

**Comment by baldarn** [comment]
@celynw I was adding this addon just for fun

would you like to merge yours in this collection? that would benefit the community ;)

what do you think @alexbelgium ?

**Comment by alexbelgium** [comment]
Hi guys, as you want! I've put the extra parts to simplify working on several addons - I just need to change a file to update all addons ;-)

The key thing is that it works... I don't necessarily want to merge as you can keep more flexibility (and personal recognition) by having your own repo, but if you want I am not against it ! An hybrid situation is also possible by just storing the config.json in my repo and having the builder script in yours... As you want ! Or we just advertise your repo so people install it on their systems (I have a list here : https://github.com/alexbelgium/hassio-addons/issues/1112)

**Comment by baldarn** [comment]
I think is best to drop this and use @celynw addon.

I don't have much time to follow this addon, and being that @celynw is working fine I wouldn't duplicate the efforts ;)
