### ISSUE TITLE
🐛 [BirdNET-Go] HA Ingress url does not redirect to url with date

### ISSUE THREAD

**Issue by phobiac** [alexbelgium/hassio-addons#1830]
### Description

I initially reported this directly to BirdNET-Go [here](https://github.com/tphakala/birdnet-go/issues/585)

This is a small UI issue. I'm seeing it in Firefox and Edge. When initially loading the BirdNET-Go dashboard there is no date set. This can be seen in the screenshot below. This has the minor consequence of making the date navigation buttons not work at all until you set a date manually.

![Image](https://github.com/user-attachments/assets/efd64787-139b-4d7d-a044-263d7d78500b)

It ONLY occurs when accessing BirdNET-Go through the HA ingress url at https://MYHAURL/db21ed7f_birdnet-go/ingress and not through http://LOCALHOSTNAME:8080/.  When loading the dashboard directly it redirects to the URL with the date at the end, so http://LOCALHOSTNAME:8080/ becomes http://LOCALHOSTNAME:8080/#2025-04-02. It seems the Home Assistant ingress does not do that redirect?

### Reproduction steps

```bash
1. Load the default dashboard through HA Ingress
2. Try to go back one day to see what birds were detected previously
3. Notice you're unable to until you set the date field
```

### Addon Logs

```bash
Starting...
/etc/cont-init.d/00-banner.sh: executing

[34m-----------------------------------------------------------[0m
[34m Add-on: Birdnet-go[0m
[34m Realtime BirdNET soundscape analyzer[0m
[34m-----------------------------------------------------------[0m
[34m Add-on version: 0.6.4-2[0m
[32m You are running the latest version of this add-on.[0m
[34m System: Home Assistant OS 15.1[0m
[34m Architecture: aarch64 / odroid-n2[0m
[34m Home Assistant Core: 2025.3.4[0m
[34m Home Assistant Supervisor: 2025.03.4[0m
[34m-----------------------------------------------------------[0m
[34m Please, share the above information when looking for help[0m
[34m or support in, e.g., GitHub, forums[0m
[34m-----------------------------------------------------------[0m
[32m Provided by: https://github.com/alexbelgium/hassio-addons [0m
[34m-----------------------------------------------------------[0m
/etc/cont-init.d/00-global_var.sh: executing

[34mBIRDSONGS_FOLDER='/media/birdnet/'[0m
[34mCOMMAND='realtime --rtsp rtsp://CAMERAURL'[0m
Timezone set from Etc/UTC to America/New_York
/etc/cont-init.d/00-local_mounts.sh: executing

/etc/cont-init.d/00-smb_mounts.sh: executing

/etc/cont-init.d/01-config_yaml.sh: executing

Setting permissions for the config_env.yaml directory

[32mLoad environment variables from /config/config_env.yaml if existing[0m
[32mIf accessing the file with filebrowser it should be mapped to /addon_configs/db21ed7f_birdnet-go/config_env.yaml[0m
[32m---------------------------------------------------------[0m

[32mWiki here on how to use : github.com/alexbelgium/hassio-addons/wiki/Add‐ons-feature-:-add-env-variables[0m
[34mTZ='America/New_York'[0m
/etc/cont-init.d/01-custom_script.sh: executing

[32mExecute /addon_configs/db21ed7f_birdnet-go/birdnet-go.sh if existing[0m
[32mWiki here : github.com/alexbelgium/hassio-addons/wiki/Add-ons-feature-:-customisation[0m
/etc/cont-init.d/01-structure.sh: executing
[11:19:15] INFO: [32m... audio clips saved to /media/birdnet according to addon options[0m
[11:19:15] INFO: [32mCorrecting configuration for defaults[0m
[11:19:16] INFO: [32m... database is located in /config/config.yaml[0m
/etc/cont-init.d/32-nginx_ingress.sh: executing
Adapting for ingress
/etc/cont-init.d/33-mariadb.sh: executing
/etc/cont-init.d/33-mqtt.sh: executing
[32m---[0m
[33mMQTT addon is active on your system! Add the MQTT details below to the Birdnet-go config.yaml :[0m
[34mMQTT user : addons[0m
[34mMQTT password : PASSWORD[0m
[34mMQTT broker : tcp://core-mosquitto:1883[0m
[32m---[0m
/etc/cont-init.d/99-run.sh: executing
 
[11:19:17] INFO: [32mALSA_CARD option is set to null. If the microphone doesn't work, please adapt it[0m
[11:19:17] INFO: [32mStarting app...[0m
🐦 [37mBirdNET-Go nightly-20250315 (built: 2025-03-19T09:13:54Z), using config file: /root/.config/birdnet-go/config.yaml[0m
BirdNET GLOBAL 6K V2.4 FP32 model initialized, using 6 threads of available 6 CPUs
System details: linux debian 12.10 on  hardware
Starting analyzer in realtime mode. Threshold: 0.85, overlap: 0, sensitivity: 1, interval: 15
2025/04/02 11:19:18 ✅ Connected to MQTT broker: tcp://core-mosquitto:1883
Logging disabled
2025/04/02 11:19:19 JSON API v2 initialized at /api/v2
HTTP server started on port 8080 (AutoTLS: false)
⇨ http server started on [::]:8080
2025/04/02 11:19:19 ⬆️ Starting FFmpeg with command: /usr/bin/ffmpeg -rtsp_transport tcp -i rtsp://CAMERAURL -loglevel error -vn -f s16le -ar 48000 -ac 1 -hide_banner pipe:1
2025/04/02 11:19:19 Clip retention policy: age
2025/04/02 11:19:19 ✅ FFmpeg started successfully for RTSP source rtsp://CAMERAURL
[11:19:19] INFO: [32mStarting NGinx...[0m
2025/04/02 11:19:32 Finished initializing BirdImageCache (58 species needed images)
```

### Architecture

amd64

### OS

HAos

**Comment by alexbelgium** [comment]
Hi, I spent quite some time with this issue when setting up the addon. The issue is that # part of the url is not passed by the nginx proxy. There is no way that I saw to make the navigation work already it is quite a hack to trick the system to show the detections for the current date!

**Comment by phobiac** [comment]
I tried looking over the nginx config for the addon but it seems a little complicated, I'll be honest that I lack understanding of all it is doing. I definitely see you've been fighting to get this working though.

For whatever it's worth, I solved this for myself by setting the WebUI port in the addon config and used my own local nginx to create a url to point at birdnet and then added that url to my dashboard instead. That is working exactly as expected for me and doesn't have this issue occurring. I will note one odd thing, instead of the url ending with 

In case this helps at all here's the relevant nginx configurations I'm using.

````
server {
  listen 443 ssl;
  listen [::]:443 ssl;
  server_name birdnet.mywebsite.com;

  location / {
    include /config/nginx/proxy.conf;
    include /config/nginx/resolver.conf;
    include /config/nginx/localonly.conf;
    set $upstream_app homeassistant-hostname;
    set $upstream_port 8080;
    set $upstream_proto http;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;
 
  }

}
````

proxy.conf
````
# Timeout if the real server is dead
proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;

# Proxy Connection Settings
proxy_buffers 32 4k;
proxy_connect_timeout 240;
proxy_headers_hash_bucket_size 128;
proxy_headers_hash_max_size 1024;
proxy_http_version 1.1;
proxy_read_timeout 240;
proxy_redirect http:// $scheme://;
proxy_send_timeout 240;

# Proxy Cache and Cookie Settings
proxy_cache_bypass $cookie_session;
#proxy_cookie_path / "/; Secure"; # enable at your own risk, may break certain apps
proxy_no_cache $cookie_session;

# Proxy Header Settings
proxy_set_header Connection $connection_upgrade;
proxy_set_header Early-Data $ssl_early_data;
proxy_set_header Host $host;
proxy_set_header Proxy "";
proxy_set_header Upgrade $http_upgrade;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Host $host;
proxy_set_header X-Forwarded-Method $request_method;
proxy_set_header X-Forwarded-Port $server_port;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Forwarded-Server $host;
proxy_set_header X-Forwarded-Ssl on;
proxy_set_header X-Forwarded-Uri $request_uri;
proxy_set_header X-Original-Method $request_method;
proxy_set_header X-Original-URL $scheme://$http_host$request_uri;
proxy_set_header X-Real-IP $remote_addr;
````

localonly.conf just has allow/deny directives and resolver.conf is auto-generated so I don't think they are relevant.

**Comment by alexbelgium** [comment]
Thanks! I've tried using your nginx code but it still doesn't work with ingress - I think the homeassistant layer strips part of the url which prevents the correct definition of the first page...

**Comment by aav7fl** [comment]
I think I fixed this.

I had a PR merged that where it prevents the main dashboard page from pushing a different URL (unless you manually start changing the calendar).

It was just included in the latest nightly release: 

https://github.com/tphakala/birdnet-go/releases/tag/nightly-20250406

Just note that because there is no cache clearing mechanism in BirdNET-Go, you'll need to manually clear the cache in your browser/device or just wait it out. (this tripped me up at first after I deployed a new build and thought it wasn't working).

Let me know if that worked after the cache gets cleared. 😄

**Comment by phobiac** [comment]
Add-on version: 0.6.4-3
🐦 BirdNET-Go nightly-20250406-9-gd8891ea (built: 2025-04-07T00:32:48Z), using config file: /root/.config/birdnet-go/config.yaml

Fully cleared all site data for my home assistant instance and checked, and just to be sure loaded it up in a freshly installed web browser to double check... unfortunately the HA ingress is still not loading today's date.

**Comment by aav7fl** [comment]
> Add-on version: 0.6.4-3
> 🐦 BirdNET-Go nightly-20250406-9-gd8891ea (built: 2025-04-07T00:32:48Z), using config file: /root/.config/birdnet-go/config.yaml
> 
> Fully cleared all site data for my home assistant instance and checked, and just to be sure loaded it up in a freshly installed web browser to double check... unfortunately the HA ingress is still not loading today's date.

That's so odd. Can you tell if it's still redirecting or not in your logs?

**Comment by phobiac** [comment]
From the addon logs shown through HA, I get a flurry of activity when the addon webui is loaded through the HA ingress URL
````
[10/Apr/2025:13:32:20 -0400] 200 127.0.0.1, 172.30.32.1(172.30.32.2) GET /api/v1/top-birds?date=&_csrf=dMSBVILEeYiGlJQNsTaQhYgfIVdWIMSf HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:137.0) Gecko/20100101 Firefox/137.0)
[10/Apr/2025:13:32:20 -0400] 200 127.0.0.1, 172.30.32.1(172.30.32.2) GET /api/v1/detections/recent?numDetections=5&_csrf=dMSBVILEeYiGlJQNsTaQhYgfIVdWIMSf HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:137.0) Gecko/20100101 Firefox/137.0)
[10/Apr/2025:13:32:20 -0400] 429 127.0.0.1, 172.30.32.1(172.30.32.2) GET /api/v1/audio-level HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:137.0) Gecko/20100101 Firefox/137.0)
[10/Apr/2025:13:32:21 -0400] 200 127.0.0.1, 172.30.32.1(172.30.32.2) GET /api/v1/media/spectrogram?clip=2025/04/thryothorus_ludovicianus_72p_20250410T133153Z.m4a HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:137.0) Gecko/20100101 Firefox/137.0)
... cutting some more lines that are basically the same ...
2025/04/10 13:34:37 Total time for processing all notes: 2.670136ms
2025/04/10 13:34:38 Retrieved 5 detections in 1.262398ms
````

Loading the webui using directly through http://homeassistanthostname:8080 (which continues to load today's date fine), I only get
````
025/04/10 13:36:51 Total time for processing all notes: 2.001769ms
2025/04/10 13:36:51 Retrieved 5 detections in 1.484493ms
````

So there's definitely something different with how the addon nginx is handling things going through HA ingress, but I can't determine what exactly it is.

**Comment by ghisch** [comment]
Could it be the same reason why the Birdnet-Go Analytics -> Overview dashboard is broken through HA but works when accessing Birdnet-Go directly locally ?

**Comment by alexbelgium** [comment]
The biggest issue is that birdnet-go is not considering subpath by default. Therefore all elements must be done manually : 
- For date the issue is that some elements (such as date) are handled by # in the url, which is not supported by nginx
- For overview it should be fixed now

**Comment by alexbelgium** [comment]
mmh curiously b-go cannot recognize my rtsp streams so I can't test but it should work for overview

**Comment by ghisch** [comment]
I think your last PR help a little, but I still have issues. /api/v2/analytics calls are all 404.

I can create another issue if you prefer

I'm on nightly-20250718-2


<img width="943" height="573" alt="Image" src="https://github.com/user-attachments/assets/1ed623ec-35b2-4506-8e84-34075f91d9a6" />

**Comment by alexbelgium** [comment]
Thanks I'll try a blanket rewrite of /api/v1 and /api/v2

**Comment by ghisch** [comment]
The last update (nightly-20250718-3) breaks access to Birdnet-go from HA

<img width="581" height="108" alt="Image" src="https://github.com/user-attachments/assets/1e01dc09-c067-4f85-9d74-dc0675aa5f96" />

<img width="1073" height="712" alt="Image" src="https://github.com/user-attachments/assets/44378a06-e20d-43b3-afde-49d393575f74" />

**Comment by alexbelgium** [comment]
It seems the only 2 things that can't be fixed at this stage is sound streaming (uses POST that doesn't seem to be supported by nginx proxy) and the date (as initiated by a hash). Normally all the rest should work (tested)

**Comment by alexbelgium** [comment]
I've likely found a solution for the date by injecting it manually on load

**Comment by ghisch** [comment]
on nightly-20250718-6, the date on the main page works, the analytics->overview dashboard works as well 👍 
Thanks @alexbelgium, well done !

**Comment by alexbelgium** [comment]
Thanks for the feedback! I'll close as the initial main point is done
