### ISSUE TITLE
❓ [openproject] Update to Version 16

### ISSUE THREAD

**Issue by unit247** [alexbelgium/hassio-addons#1881]
**Openproject**

name: Update to current Version 16.0
about: Update
title: ''
labels: ''
assignees: ''

---

**Which addon?**

[Openproject](https://github.com/alexbelgium/hassio-addons/blob/master/openproject) : Openproject for Home Assistant

**Addon or app?**

Addon

**Describe the solution you'd like**

The Addon ist currently on Version 14.1, i kindly ask you to update to Version 16.0
https://www.openproject.org/docs/release-notes/16-0-0/

**Comment by alexbelgium** [comment]
Hi I’ve adapted the updater it should be updated soon

**Comment by ash286** [comment]
I think it's not updated. My openproject addon shows `Current version: 16.0` but openproject UI shows it's still `14.1.0`. See the screenshots below. (Btw, I'm really excited to see this update, Thanks. I hoped that the update would solve the hostname and url issue but it hasn't)

Add-on version screenshot:
![Image](https://github.com/user-attachments/assets/dbfeffe2-bed0-4ac4-af61-319aafa00505)


OpenProject Info version screenshot:
![Image](https://github.com/user-attachments/assets/dd49b5d8-2a38-49a3-8990-b722ba13947c)

**Comment by alexbelgium** [comment]
Thanks indeed I've pushed a new version

**Comment by unit247** [comment]
> Thanks indeed I've pushed a new version

Thank you for the quick update. But now it does not boot up anymore.

I just get an error message: "Invalid host_name configuration" 

i uninstalled it and deleted the configuration, then installed it. still the same error

**Comment by alexbelgium** [comment]
Fixed in latest : be sure to fill the addon options configuration (especially the hostname part that must be the address of access + port - for example 192.1.1.1:8000)

Not sure it will migrate your database though - it all depends if openproject 14 and 16 were using the same psql

**Comment by ash286** [comment]
> Fixed in latest : be sure to fill the addon options configuration (especially the hostname part that must be the address of access + port - for example 192.1.1.1:8000)
> 
> Not sure it will migrate your database though - it all depends if openproject 14 and 16 were using the same psql

Is the fix pushed in version `16.0-3` or there's a new version after that?

**Comment by alexbelgium** [comment]
In version -4

**Comment by ash286** [comment]
> In version -4

It's working great. Thanks 👍 
I'm curious, how did you solve the issue of config file not being parsed in openproject 14 or was that the issue of apache in that version?

Is it possible to parse `OPENPROJECT_ATTACHMENTS__STORAGE__PATH` variable from the addon config ? I tied via configuration as well as `/config/config.yaml`. New variable goes into env.py but doesn't do anything. Alternative is to pass `-v /var/lib/openproject/assets:/var/openproject/assets` from docker run command as below and without that data get erased upon addon restart. ([openproject doc ref](https://www.openproject.org/docs/installation-and-operations/installation/docker/#using-this-container-in-production))

```
docker run -d -p 8080:80 --name openproject \
  -e OPENPROJECT_HOST__NAME=openproject.example.com \
  -e OPENPROJECT_SECRET_KEY_BASE=secret \
  -v /var/lib/openproject/pgdata:/var/openproject/pgdata \
  -v /var/lib/openproject/assets:/var/openproject/assets \
  openproject/openproject:15
```


All data seems to have migrated fine but OpenPrject says it'll require  PgSQL 16. See the message below from the UI:

```
Starting with OpenProject 16.0, PostgreSQL 16 is required to use OpenProject. Your installation will remain functional with your current database, but anticipate incompatability in future releases.
We have prepared [upgrade guides for all installation methods](https://www.openproject.org/docs/installation-and-operations/misc/migration-to-postgresql17/). You can perform the upgrade ahead of the next release at any time by following the guides.

```

**Comment by alexbelgium** [comment]
Hi, to add new environment variables use this : https://github.com/alexbelgium/hassio-addons/wiki/Add%E2%80%90ons-feature-:-add-env-variables

You install the Filebrowser addon, go in the folder /addons_configs/xxx-openproject/config.yaml and add your environement variables in yaml format

Could a symlink to /config/xxx be used instead to allow for persistence ?

Regarding the psql it is embedded within their upstream container, so I do hope they will manage themselves the migration!

**Comment by ash286** [comment]
> Hi, to add new environment variables use this : https://github.com/alexbelgium/hassio-addons/wiki/Add%E2%80%90ons-feature-:-add-env-variables
> 
> You install the Filebrowser addon, go in the folder /addons_configs/xxx-openproject/config.yaml and add your environement variables in yaml format
> 

Hi, sorry my bad, I mean I already set the environment in `/addons_configs/xxx-openproject/config.yaml` and that definately passes into `env.py` and `.env` but it doesn't have any effect. I have now set the `OPENPROJECT_ATTACHMENTS__STORAGE__PATH` using Portainer.


> Regarding the psql it is embedded within their upstream container, so I do hope they will manage themselves the migration!

Great then we don't need to worry about it then.

**Comment by alexbelgium** [comment]
Hi, new version should allow custom variables from config.yaml. Just allow it some time for launching

**Comment by ash286** [comment]
I think moving `pg` to `/addons_configs/xxx-openproject/` is not really required as pgsql data never get erased upon addon restart. It's just attachments storage that folder gets erased upon addon restart. Can we please remove `99-run.sh` if it is not essential for custum variables to work?

99-run.sh seems to hang addon initialisation in loop or you think I am not waiting long enough (waited 15 minutes)

```
performing post-bootstrap initialization ... ok
syncing data to disk ... ok
Success. You can now start the database server using:
    pg_ctlcluster 13 main start
Ver Cluster Port Status Owner    Data directory              Log file
13  main    5433 down   postgres /var/lib/postgresql/13/main /var/log/postgresql/postgresql-13-main.log
-----> Database cluster already exists, not modifying.
pg_ctl: could not start server
Examine the log output.
       waiting for server to start.... stopped waiting
Error : /etc/cont-init.d/99-run.sh exiting 1
Everything started!
performing post-bootstrap initialization ... ok
syncing data to disk ... ok
Success. You can now start the database server using:
    pg_ctlcluster 13 main start
Ver Cluster Port Status Owner    Data directory              Log file
13  main    5433 down   postgres /var/lib/postgresql/13/main /var/log/postgresql/postgresql-13-main.log
-----> Database cluster already exists, not modifying.
pg_ctl: could not start server
Examine the log output.
       waiting for server to start.... stopped waiting
Error : /etc/cont-init.d/99-run.sh exiting 1
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
Everything started!
```

**Comment by alexbelgium** [comment]
99-run.sh is required to enable the config.yaml env exports

Mmh indeed this fails `pg_ctl: could not start server` - I'll revert to the initial paths in case it is troubling the addon

**Comment by alexbelgium** [comment]
Actually it might just be a permissions issue. I've added correct permissions in 16.0-7

**Comment by ash286** [comment]
> 99-run.sh is required to enable the config.yaml env exports

I understand. Can you please help me understand why it is necessary to move pgslql databased to `/addons_configs/xxx-openproject/` ? Can we not simply get rid of copying and moving part (lines 6-18 in 99-run.sh) and just keep the remaining if that is essential to enable config.yaml env env exports?

**Comment by alexbelgium** [comment]
Why does it bother you ? Both (/data and /config) are backuped with the addon, and stored on the same drive. The only difference is that one is reacheable for manual actions (such as seeing files and images) and the other is hidden

**Comment by ash286** [comment]
You are right. 

I think it's not a good idea to move pg database (more than 2k files and folders) for `/config` and unnecessarily expose it to `/addons_configs/xxx-openproject/`. One small error can corrupt entire database and exposing also means database can be accidently altered when `/addon_configs` mounted via samba server so I'd better like it in `/data` location. Also, why we go for a complex solution when we can have a simple solution ;) Allow me to propose another simple solution, in case we can't use custom variables from config.yaml without moving `pg`.

**Comment by alexbelgium** [comment]
Then I’ll just reuse /data. If you restore your backup and update to the latest that will be pushed this evening, it will avoid the migration.

**Comment by ash286** [comment]
Hi, so finally I was able to update openproject to -10 and I must say that it's now perfact. Also, I was thinking the otherday to put OPENPROJECT_ATTACHMENTS__STORAGE__PATH into config jason, which you did, so that everyone can benefit without specifying it and attachments wouldn't become ghost suddenlty upon addon restart (I had happened that with 14 and it was very frustrating and I had to set it through portainer everytime). I haven't quite understood the role of 99-run.sh yet but now custom env variables work with config yaml and it's fantastic.

**Comment by alexbelgium** [comment]
Glad it works. Using my entrypoint logic instead of opening directly openproject allows to run my different startup scripts. This is what I do for nearly all my addons - guess either I did not set that one up or I was a bit lazy ;-)

In those startup scripts, the 99-run.sh serves as a placeholder where https://github.com/alexbelgium/hassio-addons/blob/master/.templates/00-global_var.sh and https://github.com/alexbelgium/hassio-addons/blob/master/.templates/01-config_yaml.sh add dynamically an "export" command to the addon options, and to the elements in the config.yaml, allowing the openproject app to see those as environement variables (as it is started from the same shell than the one where the exports are done).

Now - everything should work as expected !

**Comment by ash286** [comment]
Brilliant. Thank you for helping me understand.
