### ISSUE TITLE
🐛 [resiliosync] Resilio Sync does not have permission to access this folder: /backup

### ISSUE THREAD

**Issue by FrankBakermans** [alexbelgium/hassio-addons#1909]
### Description

Hi Alex,

Love ResilioSync and I love you have created an HA addon for this.

I wanted to use resiliosync to sync my HA backups with other devices, only when I add folder /backup to resiliosync I get the error:

Resilio Sync does not have permission to access this folder

I changed the permissions on this folder to drwxrwxrwx, but still I am getting the same error.

Can you help or resolve this issue somehow?

Cheers,
Frank

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Addon Logs

```bash
no mention of /backup or the error message in the log
```

### OS

HAos

**Comment by alexbelgium** [comment]
Hi, are you using puid and guid 0 to be root ?

**Comment by FrankBakermans** [comment]
Hi,

Yes they are both 0. Also the folders created when you choose the option "New Folder" have root as owner and group.

Thanks,
Frank

**Comment by alexbelgium** [comment]
Mmh interesting I wonder why the permissions issues then. I'll deep dive a bit - I don't use the app myself.

**Comment by FrankBakermans** [comment]
Hi, 

Thanks. You should use ResilioSync, it is a brilliant app to distribute files to all kinds of devices. It is one of the few ways to get files easy onto (cr)Apple Iphone/Ipad.

Thanks again,
Frank

**Comment by alexbelgium** [comment]
I willl add the /backup folder to the addon it should solve it

**Comment by FrankBakermans** [comment]
Hi,

Thanks, I saw the update, but when try to install it I am getting the following error:

Failed to perform the action update/install. Error updating

ResilioSync: Can't install ghcr.io/alexbelgium/resiliosync-

amd64:3.0.3.1065-2: 500 Server Error for

http+docker://localhost/v1.48/images/create?tag=3.0.3.1065-

2&fromImage=ghcr.io%2Falexbelgium%2Fresiliosync-

amd64&platform=linux%2Famd64: Internal Server Error ("manifest unknown")

Thanks,
Frank

**Comment by alexbelgium** [comment]
Should be good now !

**Comment by FrankBakermans** [comment]
Hi, I was able to update, but sorry I still have the issue that Resilio Sync does not have permission to access /backup.

Do I need to change anything on the config for this?

Cheers,
Frank

**Comment by alexbelgium** [comment]
I'm stuck it doesn't seem to accept my license file downloaded from their website

I've checked however that /backup is accessible from within the container, owned by root

**Comment by FrankBakermans** [comment]
Hi, 

I just uploaded the btskey file via the Settings-License-Apply New License and that worked.

Thanks,
Frank

**Comment by alexbelgium** [comment]
Thanks, I add an old config that I needed to remove.

I've pushed a new version that adds the folder to the whitelist

**Comment by FrankBakermans** [comment]
Hi, 

It is working, I managed to add the/backup folder.

Thanks,
Frank

**Comment by alexbelgium** [comment]
I'll add a code to align the config storage to other locations, please backup before next update just in case

**Comment by FrankBakermans** [comment]
Hi, 

 

That last version does not want to start, it is giving the following error:

 

cp: cannot create regular file '/config/addons_config/resiliosync/sync.conf': No such file or directory

s6-rc: warning: unable to start service init-resilio-sync-config: command exited 1

 

Cheers,

Frank

**Comment by alexbelgium** [comment]
Thanks have you tried the latest ?

**Comment by FrankBakermans** [comment]
Hi,

 

Yes, I tried the latest this morning and it is working.

 

Thanks for your help, my HA backup is sorted.

 

Cheers,

Frank

**Comment by alexbelgium** [comment]
Great! Now it allows the config to be backuped with the addon, which is much better for users too

Thanks for the feedback

Best regards
