### ISSUE TITLE
[Firefly iii Data Importer] Impossible to create the root directory

### ISSUE THREAD

**Issue by diamant-x** [alexbelgium/hassio-addons#271]
**Which addon?**

- Addon name : Firefly iii Data Importer
- Addon version : version-0.9.0 

**Describe the bug**

Trying to navigate to any of the main menu items now results in error. Automatic import also error. Apparently tries to write a new folder or assert the config folder but fails. I think it is using wrong os.path.sep ( \ vs / ) and hence fails.

**To Reproduce**

N/A.

**System**

- Supervisor version: supervisor-2022.03.5
- Host system version: core-2022.3.6

**Full addon config**
'
```
[2022-03-27 18:19:25] production.DEBUG: csv is a valid flow, redirect to authenticate.  
192.168.10.26 - - [27/Mar/2022:18:19:25 +0200] "POST / HTTP/1.1" 302 1920 "http://hassio-ip:3474/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.55"
[2022-03-27 18:19:25] production.DEBUG: Now in AuthenticateController, calling middleware.  
[2022-03-27 18:19:25] production.DEBUG: isReadyForCSVStep("authenticate")  
[2022-03-27 18:19:25] production.DEBUG: isReadyForCSVStep: Return false  
[2022-03-27 18:19:25] production.DEBUG: redirectToCorrectCSVStep("authenticate")  
[2022-03-27 18:19:25] production.DEBUG: Return redirect to "http://hassio-ip:3474/upload"  
192.168.10.26 - - [27/Mar/2022:18:19:25 +0200] "GET /authenticate HTTP/1.1" 302 1579 "http://hassio-ip:3474/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.55"
[2022-03-27 18:19:25] production.DEBUG: isReadyForCSVStep("upload-files")  
[2022-03-27 18:19:25] production.DEBUG: isReadyForCSVStep: Return true  
[2022-03-27 18:19:25] production.DEBUG: Now at App\Http\Controllers\Import\UploadController::index  
[2022-03-27 18:19:25] production.ERROR: Impossible to create the root directory "/config/addons_config/fireflyiii_data_importer/configurations".  {"exception":"[object] (League\\Flysystem\\Exception(code: 0): Impossible to create the root directory \"/config/addons_config/fireflyiii_data_importer/configurations\".  at /var/www/html/vendor/league/flysystem/src/Adapter/Local.php:112)
[stacktrace]
#0 /var/www/html/vendor/league/flysystem/src/Adapter/Local.php(78): League\\Flysystem\\Adapter\\Local->ensureDirectory()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemManager.php(182): League\\Flysystem\\Adapter\\Local->__construct()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemManager.php(147): Illuminate\\Filesystem\\FilesystemManager->createLocalDriver()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemManager.php(115): Illuminate\\Filesystem\\FilesystemManager->resolve()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemManager.php(78): Illuminate\\Filesystem\\FilesystemManager->get()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Filesystem\\FilesystemManager->disk()
#6 /var/www/html/app/Http/Controllers/Import/UploadController.php(71): Illuminate\\Support\\Facades\\Facade::__callStatic()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Import\\UploadController->index()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\\Routing\\Route->run()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#13 /var/www/html/app/Http/Middleware/IsReadyForStep.php(54): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\UploadControllerMiddleware->handle()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(723): Illuminate\\Pipeline\\Pipeline->then()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(698): Illuminate\\Routing\\Router->runRouteWithinStack()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRoute()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(651): Illuminate\\Routing\\Router->dispatchToRoute()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#45 /var/www/html/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#49 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#51 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#52 /var/www/html/public/index.php(77): Illuminate\\Foundation\\Http\\Kernel->handle()
#53 {main}
"} 
```
'

**Comment by alexbelgium** [comment]
Hi, which was the last working version?
Thanks

**Comment by diamant-x** [comment]
Last successful auto-import was on 11th March.
I don't remember updating it, or at least I did no backup when doing so. Not sure if there was any update pushed since that date?

**Comment by alexbelgium** [comment]
Thanks, I'll investigate

**Comment by alexbelgium** [comment]
Could you please paste the full log, including the banner and the initial lines where it executes the script? The app itself hasn't changed since 11-Mar so perhaps the issue is in one of my scripts... Thanks!

**Comment by alexbelgium** [comment]
Mmh actually this could be induced by a change of /config permissions by another addon. To test that I've pushed a new version (-3) that will try to restore permissions to the directory (if that was the cause). Otherwise the full log as stated above could be useful :)

**Comment by diamant-x** [comment]
> Could you please paste the full log, including the banner and the initial lines where it executes the script? The app itself hasn't changed since 11-Mar so perhaps the issue is in one of my scripts... Thanks!

These are the initial logs (taken from Portainer log) before updating to the version -3. I'll do that this afternoon.

```
`Starting...
/etc/cont-init.d/00-aaa_dockerfile_backup.sh: executing
/etc/cont-init.d/00-banner.sh: executing
-----------------------------------------------------------
 Add-on: Firefly iii Data Importer
 Data importer for Firefly III (separate addon)
-----------------------------------------------------------
 Add-on version: version-0.9.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 7.5  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2022.3.6
 Home Assistant Supervisor: 2022.03.5
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
 https://github.com/alexbelgium/hassio-addons
-----------------------------------------------------------
/etc/cont-init.d/00-global_var.sh: executing
CONFIG_LOCATION='/config/addons_config/fireflyiii_data_importer/config.yaml'
FIREFLY_III_ACCESS_TOKEN=<removed>
FIREFLY_III_URL='http://hassio-ip:3473'
NORDIGEN_ID=<removed>
NORDIGEN_KEY=<removed>
SPECTRE_APP_ID=<removed>
SPECTRE_SECRET=<removed>
Updates='hourly'
silent='false'
Timezone set from Etc/UTC to Europe/Madrid
/etc/cont-init.d/20-folders.sh: executing
/etc/cont-init.d/90-config_yaml.sh: executing
Using config file found in /config/addons_config/fireflyiii_data_importer/config.yaml
Config file is a valid yaml
[15:24:09] INFO: Starting the app with the variables in in /config/addons_config/fireflyiii_data_importer/config.yaml
TZ=Europe/Madrid
/etc/cont-init.d/99-run.sh: executing
[15:24:10] INFO: Configurations were found in /config/addons_config/fireflyiii_data_importer/configurations, they will be loaded.
[15:24:10] INFO: hourly updates
Starting periodic command scheduler: cron.
[15:24:10] INFO: Automatic updates were requested. The files in /config/addons_config/fireflyiii_data_importer/import_files will be imported hourly.
[15:24:10] INFO: Please wait while the app is loading !
Now in entrypoint.sh for Firefly III Data Importer
Script:        1.6 (2022-02-17)
User:          'root'
Group:         'root'
Working dir:   '/var/www/html'
Build number:  97
Build date:    21-02-2022 20:13:33 CET
Now parsing _FILE variables.
done!
Firefly III data importer v0.9.0
PHP: cli 8.0.13 Linux
Will now run Apache web server:
[Sat Mar 26 15:24:20.898386 2022] [mpm_prefork:notice] [pid 309] AH00163: Apache/2.4.38 (Debian) configured -- resuming normal operations
[Sat Mar 26 15:24:20.898557 2022] [core:notice] [pid 309] AH00094: Command line: 'apache2 -D FOREGROUND'
[2022-03-26 15:24:50] production.DEBUG: Now in App\Http\Controllers\IndexController::index  
[2022-03-26 15:24:50] production.DEBUG: App\Services\Shared\Authentication\SecretManager::hasValidSecrets  
192.168.10.26 - - [26/Mar/2022:15:24:50 +0100] "GET / HTTP/1.1" 200 3226 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.52"
[2022-03-26 15:24:51] production.DEBUG: Now at App\Http\Controllers\TokenController::doValidate  
[2022-03-26 15:24:51] production.DEBUG: isReadyForCSVStep("service-validation")  
[2022-03-26 15:24:51] production.DEBUG: isReadyForCSVStep: Return true  
[2022-03-26 15:24:51] production.DEBUG: isReadyForCSVStep("service-validation")  
[2022-03-26 15:24:51] production.DEBUG: isReadyForCSVStep: Return true  
[2022-03-26 15:24:51] production.DEBUG: Now at App\Services\Nordigen\AuthenticationValidator::validate  
[2022-03-26 15:24:51] production.DEBUG: Now at App\Services\Spectre\AuthenticationValidator::validate  
[2022-03-26 15:24:51] production.DEBUG: No Spectre App ID in hasAppId(), will return config variable.  
[2022-03-26 15:24:51] production.DEBUG: No Spectre secret in hasSecret(), will return config variable.  
[2022-03-26 15:24:51] production.DEBUG: Now at App\Services\Nordigen\TokenManager::hasValidRefreshToken  
[2022-03-26 15:24:51] production.DEBUG: No Nordigen refresh token, so return false.  
[2022-03-26 15:24:51] production.DEBUG: Now at App\Services\Nordigen\TokenManager::hasExpiredRefreshToken  
[2022-03-26 15:24:51] production.DEBUG: No refresh token, so return false.  
[2022-03-26 15:24:51] production.DEBUG: Now at App\Services\Nordigen\TokenManager::getNewTokenSet  
[2022-03-26 15:24:51] production.DEBUG: setParameters  
[2022-03-26 15:24:51] production.DEBUG: Result is {"result":"OK","message":null} 
192.168.10.26 - - [26/Mar/2022:15:24:51 +0100] "GET /token/validate HTTP/1.1" 200 1139 "http://hassio-ip:3474/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.52"
192.168.10.26 - - [26/Mar/2022:15:24:51 +0100] "GET /validate/spectre HTTP/1.1" 200 1125 "http://hassio-ip:3474/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.52"
192.168.10.26 - - [26/Mar/2022:15:24:51 +0100] "GET /validate/nordigen HTTP/1.1" 200 1125 "http://hassio-ip:3474/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.52"
[2022-03-26 15:24:52] production.DEBUG: Now in App\Http\Controllers\IndexController::postIndex  
[2022-03-26 15:24:52] production.DEBUG: nordigen is a valid flow, redirect to authenticate.  
192.168.10.26 - - [26/Mar/2022:15:24:52 +0100] "POST / HTTP/1.1" 302 1952 "http://hassio-ip:3474/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.52"
[2022-03-26 15:24:52] production.DEBUG: Now in AuthenticateController, calling middleware.  
[2022-03-26 15:24:52] production.DEBUG: isReadyForNordigenStep("authenticate")  
[2022-03-26 15:24:52] production.DEBUG: isReadyForNordigenStep: Return true  
[2022-03-26 15:24:52] production.DEBUG: Now at App\Services\Nordigen\AuthenticationValidator::validate  
[2022-03-26 15:24:52] production.DEBUG: Now at App\Services\Nordigen\TokenManager::hasValidRefreshToken  
[2022-03-26 15:24:52] production.DEBUG: Now at App\Services\Nordigen\TokenManager::hasValidAccessToken  
[2022-03-26 15:24:52] production.DEBUG: Nordigen token is valid until 2022-03-27 16:24:51  
[2022-03-26 15:24:52] production.DEBUG: Nordigen token is valid.  
192.168.10.26 - - [26/Mar/2022:15:24:52 +0100] "GET /authenticate HTTP/1.1" 302 1579 "http://hassio-ip:3474/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.52"
[2022-03-26 15:24:52] production.DEBUG: isReadyForNordigenStep("upload-files")  
[2022-03-26 15:24:52] production.DEBUG: isReadyForNordigenStep: Return true  
[2022-03-26 15:24:52] production.DEBUG: Now at App\Http\Controllers\Import\UploadController::index  
[2022-03-26 15:24:52] production.ERROR: Impossible to create the root directory "/config/addons_config/fireflyiii_data_importer/configurations".  {"exception":"[object] (League\\Flysystem\\Exception(code: 0): Impossible to create the root directory \"/config/addons_config/fireflyiii_data_importer/configurations\".  at /var/www/html/vendor/league/flysystem/src/Adapter/Local.php:112)`
```

**Comment by diamant-x** [comment]
> Mmh actually this could be induced by a change of /config permissions by another addon. To test that I've pushed a new version (-3) that will try to restore permissions to the directory (if that was the cause). Otherwise the full log as stated above could be useful :)

Same issue occurs with -v3. Below logs with both a 'scheduled' attempt to import the files, as well as a manuall navigation in the web. 

I'm also pasting the ls -la of the dir from the command line of the container, in case you identify something wrong with permissions and such

```
root@db21ed7f-fireflyiii-data-importer:/config/addons_config/fireflyiii_data_importer# ls -la
total 20
drwxr-xr-x  4 www-data www-data 4096 Feb  7 20:18 .
drwxr-xr-x 10 root     root     4096 Mar 12 20:34 ..
-rwxr-xr-x  1 www-data www-data  528 Feb  4 17:52 config.yaml
drwxr-xr-x  2 www-data www-data 4096 Mar  7 21:35 configurations
drwxr-xr-x  2 www-data www-data 4096 Mar 11 18:47 import_files
```

```
root@db21ed7f-fireflyiii-data-importer:/config/addons_config/fireflyiii_data_importer/configurations# ls -la
total 16
drwxr-xr-x 2 www-data www-data 4096 Mar  7 21:35 .
drwxr-xr-x 4 www-data www-data 4096 Feb  7 20:18 ..
-rwxr-xr-x 1 www-data www-data 1144 Mar  7 21:35 Nordigen_config_15days.json
-rwxr-xr-x 1 www-data www-data 1179 Feb  2 20:59 Nordigen_config_2022-02-02.json
```

```
root@db21ed7f-fireflyiii-data-importer:/config/addons_config/fireflyiii_data_importer/import_files# ls -la
total 28
drwxr-xr-x 2 www-data www-data 4096 Mar 11 18:47 .
drwxr-xr-x 4 www-data www-data 4096 Feb  7 20:18 ..
-rwxr-xr-x 1 www-data www-data 1496 Mar 11 18:47 CSVfile1.csv
-rwxr-xr-x 1 www-data www-data  975 Feb 15 20:11 CSVfile1.json
-rwxr-xr-x 1 www-data www-data 1144 Mar 11 18:59 Nordigen_config_15days.json
-rwxr-xr-x 1 www-data www-data    3 Mar  7 23:08 CSVFile2.csv
-rwxr-xr-x 1 www-data www-data 1211 Feb  4 17:51 CSVfile2.json
```

```
Timezone set from Etc/UTC to Europe/Madrid
/etc/cont-init.d/20-folders.sh: executing
/etc/cont-init.d/90-config_yaml.sh: executing
Using config file found in /config/addons_config/fireflyiii_data_importer/config.yaml
Config file is a valid yaml
grep: config.yaml: No such file or directory
[13:55:03] INFO: Starting the app with the variables in in /config/addons_config/fireflyiii_data_importer/config.yaml
TZ=Europe/Madrid
/etc/cont-init.d/99-run.sh: executing
[13:55:04] INFO: Configurations were found in /config/addons_config/fireflyiii_data_importer/configurations, they will be loaded.
[13:55:04] INFO: hourly updates
Starting periodic command scheduler: cron.
[13:55:04] INFO: Automatic updates were requested. The files in /config/addons_config/fireflyiii_data_importer/import_files will be imported hourly.
[13:55:04] INFO: Please wait while the app is loading !
Now in entrypoint.sh for Firefly III Data Importer
Script:        1.6 (2022-02-17)
User:          'root'
Group:         'root'
Working dir:   '/var/www/html'
Build number:  97
Build date:    21-02-2022 20:13:33 CET
Now parsing _FILE variables.
done!
Firefly III data importer v0.9.0
PHP: cli 8.0.13 Linux
Will now run Apache web server:
[Mon Mar 28 13:55:16.220670 2022] [mpm_prefork:notice] [pid 309] AH00163: Apache/2.4.38 (Debian) configured -- resuming normal operations
[Mon Mar 28 13:55:16.220818 2022] [core:notice] [pid 309] AH00094: Command line: 'apache2 -D FOREGROUND'
[14:17:01] INFO: Running update according to defined schedule. Files located in /config/addons_config/fireflyiii_data_importer will be imported
[2022-03-28 14:17:02] production.ERROR: App\Console\Commands\AutoImport::isAllowedPath(): Argument #1 ($path) must be of type string, bool given, called in /var/www/html/app/Console/Commands/AutoImport.php on line 69 {"exception":"[object] (TypeError(code: 0): App\\Console\\Commands\\AutoImport::isAllowedPath(): Argument #1 ($path) must be of type string, bool given, called in /var/www/html/app/Console/Commands/AutoImport.php on line 69 at /var/www/html/app/Console/HaveAccess.php:70)

[stacktrace]
#0 /var/www/html/app/Console/Commands/AutoImport.php(69): App\\Console\\Commands\\AutoImport->isAllowedPath()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Console\\Commands\\AutoImport->handle()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#7 /var/www/html/vendor/symfony/console/Command/Command.php(298): Illuminate\\Console\\Command->execute()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#9 /var/www/html/vendor/symfony/console/Application.php(1015): Illuminate\\Console\\Command->run()
#10 /var/www/html/vendor/symfony/console/Application.php(299): Symfony\\Component\\Console\\Application->doRunCommand()
#11 /var/www/html/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(94): Symfony\\Component\\Console\\Application->run()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#14 /var/www/html/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#15 {main}
"} 
In HaveAccess.php line 70:
                                                                               
  App\Console\Commands\AutoImport::isAllowedPath(): Argument #1 ($path) must   
  be of type string, bool given, called in /var/www/html/app/Console/Commands  
  /AutoImport.php on line 69                                                   
                                                                               
[2022-03-28 15:00:06] production.DEBUG: Now in App\Http\Controllers\IndexController::index  
[2022-03-28 15:00:06] production.DEBUG: App\Services\Shared\Authentication\SecretManager::hasValidSecrets  
192.168.10.26 - - [28/Mar/2022:15:00:06 +0200] "GET / HTTP/1.1" 200 3223 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.55"
192.168.10.26 - - [28/Mar/2022:15:00:06 +0200] "GET /fa/css/all.min.css HTTP/1.1" 200 13028 "http://hassio-ip:3474/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.55"
192.168.10.26 - - [28/Mar/2022:15:00:06 +0200] "GET /js/popper.min.js?version=0.9.0 HTTP/1.1" 200 7080 "http://hassio-ip:3474/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.55"
192.168.10.26 - - [28/Mar/2022:15:00:06 +0200] "GET /js/bootstrap.min.js?version=0.9.0 HTTP/1.1" 200 16729 "http://hassio-ip:3474/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.55"
192.168.10.26 - - [28/Mar/2022:15:00:06 +0200] "GET /js/jquery-3.6.0.min.js?version=0.9.0 HTTP/1.1" 200 31271 "http://hassio-ip:3474/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.55"
192.168.10.26 - - [28/Mar/2022:15:00:06 +0200] "GET /css/bootstrap-dark.min.css?version=0.9.0 HTTP/1.1" 200 31464 "http://hassio-ip:3474/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.55"
192.168.10.26 - - [28/Mar/2022:15:00:07 +0200] "GET /fa/webfonts/fa-solid-900.woff2 HTTP/1.1" 200 79748 "http://hassio-ip:3474/fa/css/all.min.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.55"
[2022-03-28 15:00:07] production.DEBUG: Now at App\Http\Controllers\TokenController::doValidate  
[2022-03-28 15:00:07] production.DEBUG: isReadyForCSVStep("service-validation")  
[2022-03-28 15:00:07] production.DEBUG: isReadyForCSVStep: Return true  
[2022-03-28 15:00:07] production.DEBUG: isReadyForCSVStep("service-validation")  
[2022-03-28 15:00:07] production.DEBUG: isReadyForCSVStep: Return true  
[2022-03-28 15:00:07] production.DEBUG: Now at App\Services\Nordigen\AuthenticationValidator::validate  
[2022-03-28 15:00:07] production.DEBUG: Now at App\Services\Spectre\AuthenticationValidator::validate  
[2022-03-28 15:00:07] production.DEBUG: No Spectre App ID in hasAppId(), will return config variable.  
[2022-03-28 15:00:07] production.DEBUG: Now at App\Services\Nordigen\TokenManager::hasValidRefreshToken  
[2022-03-28 15:00:07] production.DEBUG: No Nordigen refresh token, so return false.  
[2022-03-28 15:00:07] production.DEBUG: No Spectre secret in hasSecret(), will return config variable.  
[2022-03-28 15:00:07] production.DEBUG: Now at App\Services\Nordigen\TokenManager::hasExpiredRefreshToken  
[2022-03-28 15:00:07] production.DEBUG: No refresh token, so return false.  
[2022-03-28 15:00:07] production.DEBUG: Now at App\Services\Nordigen\TokenManager::getNewTokenSet  
[2022-03-28 15:00:07] production.DEBUG: setParameters  
192.168.10.26 - - [28/Mar/2022:15:00:07 +0200] "GET /favicon.ico HTTP/1.1" 200 279 "http://hassio-ip:3474/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.55"
[2022-03-28 15:00:07] production.DEBUG: Result is {"result":"OK","message":null} 
192.168.10.26 - - [28/Mar/2022:15:00:07 +0200] "GET /token/validate HTTP/1.1" 200 1139 "http://hassio-ip:3474/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.55"
192.168.10.26 - - [28/Mar/2022:15:00:07 +0200] "GET /validate/spectre HTTP/1.1" 200 1124 "http://hassio-ip:3474/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.55"
192.168.10.26 - - [28/Mar/2022:15:00:07 +0200] "GET /validate/nordigen HTTP/1.1" 200 1124 "http://hassio-ip:3474/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.55"
[2022-03-28 15:00:13] production.DEBUG: Now in App\Http\Controllers\IndexController::postIndex  
[2022-03-28 15:00:13] production.DEBUG: nordigen is a valid flow, redirect to authenticate.  
192.168.10.26 - - [28/Mar/2022:15:00:13 +0200] "POST / HTTP/1.1" 302 1952 "http://hassio-ip:3474/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.55"
127.0.0.1 - - [28/Mar/2022:15:00:13 +0200] "OPTIONS * HTTP/1.0" 200 110 "-" "Apache/2.4.38 (Debian) (internal dummy connection)"
[2022-03-28 15:00:13] production.DEBUG: Now in AuthenticateController, calling middleware.  
[2022-03-28 15:00:13] production.DEBUG: isReadyForNordigenStep("authenticate")  
[2022-03-28 15:00:13] production.DEBUG: isReadyForNordigenStep: Return true  
[2022-03-28 15:00:13] production.DEBUG: Now at App\Services\Nordigen\AuthenticationValidator::validate  
[2022-03-28 15:00:13] production.DEBUG: Now at App\Services\Nordigen\TokenManager::hasValidRefreshToken  
[2022-03-28 15:00:13] production.DEBUG: Now at App\Services\Nordigen\TokenManager::hasValidAccessToken  
[2022-03-28 15:00:13] production.DEBUG: Nordigen token is valid until 2022-03-29 15:00:11  
[2022-03-28 15:00:13] production.DEBUG: Nordigen token is valid.  
192.168.10.26 - - [28/Mar/2022:15:00:13 +0200] "GET /authenticate HTTP/1.1" 302 1579 "http://hassio-ip:3474/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.55"
[2022-03-28 15:00:13] production.DEBUG: isReadyForNordigenStep("upload-files")  
[2022-03-28 15:00:13] production.DEBUG: isReadyForNordigenStep: Return true  
[2022-03-28 15:00:13] production.DEBUG: Now at App\Http\Controllers\Import\UploadController::index  
[2022-03-28 15:00:13] production.ERROR: Impossible to create the root directory "/config/addons_config/fireflyiii_data_importer/configurations".  {"exception":"[object] (League\\Flysystem\\Exception(code: 0): Impossible to create the root directory \"/config/addons_config/fireflyiii_data_importer/configurations\".  at /var/www/html/vendor/league/flysystem/src/Adapter/Local.php:112)

[stacktrace]
#0 /var/www/html/vendor/league/flysystem/src/Adapter/Local.php(78): League\\Flysystem\\Adapter\\Local->ensureDirectory()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemManager.php(182): League\\Flysystem\\Adapter\\Local->__construct()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemManager.php(147): Illuminate\\Filesystem\\FilesystemManager->createLocalDriver()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemManager.php(115): Illuminate\\Filesystem\
```

**Comment by alexbelgium** [comment]
Thanks for all the details. I'll try to understand :-) permissions issue would have been an easy way out. I see several different issue in the log, so I'll start there.

**Comment by alexbelgium** [comment]
Writing this for myself for troubleshooting

First error :
```
"[2022-03-28 14:17:02] production.ERROR: App\Console\Commands\AutoImport::isAllowedPath(): Argument #1 ($path) must be of type string, bool given, called in /var/www/html/app/Console/Commands/AutoImport.php on line 69 {"exception":"[object] (TypeError(code: 0): App\\Console\\Commands\\AutoImport::isAllowedPath(): Argument #1 ($path) must be of type string, bool given, called in /var/www/html/app/Console/Commands/AutoImport.php on line 69 at /var/www/html/app/Console/HaveAccess.php:70)"
```
Location : https://github.com/firefly-iii/data-importer/blob/9c696b979a55e676f4c9aa04263caae7fdf2bfe3/app/Console/Commands/AutoImport.php#L69

For some reason, the realpath function here (https://github.com/firefly-iii/data-importer/blob/9c696b979a55e676f4c9aa04263caae7fdf2bfe3/app/Console/Commands/AutoImport.php#L68) can't read the directory and returns therefore a "false" statement which triggers the error.

In parallel I've pushed a new version -4 that changes back the user executing the script from www-data to root, but I don't think it will solve the issue

**Comment by diamant-x** [comment]
> In parallel I've pushed a new version -4 that changes back the user executing the script from www-data to root, but I don't think it will solve the issue

I just installed and tried navigating to the web menu to load the files with same error (below).
Thanks for looking at it!

```
-----------------------------------------------------------
 Add-on version: version-0.9.0-4
 You are running the latest version of this add-on.
 System: Home Assistant OS 7.5  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2022.3.6
 Home Assistant Supervisor: 2022.03.5
<-removed this part for briefty->
Will now run Apache web server:
[Mon Mar 28 21:49:16.624598 2022] [mpm_prefork:notice] [pid 309] AH00163: Apache/2.4.38 (Debian) configured -- resuming normal operations
[Mon Mar 28 21:49:16.624769 2022] [core:notice] [pid 309] AH00094: Command line: 'apache2 -D FOREGROUND'
[2022-03-28 22:01:18] production.DEBUG: Now in App\Http\Controllers\IndexController::index  
[2022-03-28 22:01:18] production.DEBUG: App\Services\Shared\Authentication\SecretManager::hasValidSecrets  
192.168.10.26 - - [28/Mar/2022:22:01:18 +0200] "GET / HTTP/1.1" 200 3223 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.55"
[2022-03-28 22:01:19] production.DEBUG: Now at App\Http\Controllers\TokenController::doValidate  
[2022-03-28 22:01:19] production.DEBUG: isReadyForNordigenStep("service-validation")  
[2022-03-28 22:01:19] production.DEBUG: isReadyForNordigenStep("service-validation")  
[2022-03-28 22:01:19] production.DEBUG: isReadyForNordigenStep: Return true  
[2022-03-28 22:01:19] production.DEBUG: isReadyForNordigenStep: Return true  
[2022-03-28 22:01:19] production.DEBUG: Now at App\Services\Spectre\AuthenticationValidator::validate  
[2022-03-28 22:01:19] production.DEBUG: Now at App\Services\Nordigen\AuthenticationValidator::validate  
[2022-03-28 22:01:19] production.DEBUG: No Spectre App ID in hasAppId(), will return config variable.  
[2022-03-28 22:01:19] production.DEBUG: No Spectre secret in hasSecret(), will return config variable.  
[2022-03-28 22:01:19] production.DEBUG: Now at App\Services\Nordigen\TokenManager::hasValidRefreshToken  
[2022-03-28 22:01:19] production.DEBUG: No Nordigen refresh token, so return false.  
[2022-03-28 22:01:19] production.DEBUG: Now at App\Services\Nordigen\TokenManager::hasExpiredRefreshToken  
[2022-03-28 22:01:19] production.DEBUG: No refresh token, so return false.  
[2022-03-28 22:01:19] production.DEBUG: Now at App\Services\Nordigen\TokenManager::getNewTokenSet  
[2022-03-28 22:01:19] production.DEBUG: setParameters  
[2022-03-28 22:01:19] production.DEBUG: Result is {"result":"OK","message":null} 
192.168.10.26 - - [28/Mar/2022:22:01:19 +0200] "GET /token/validate HTTP/1.1" 200 1139 "http://hassio-ip:3474/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.55"
192.168.10.26 - - [28/Mar/2022:22:01:19 +0200] "GET /validate/nordigen HTTP/1.1" 200 1125 "http://hassio-ip:3474/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.55"
192.168.10.26 - - [28/Mar/2022:22:01:19 +0200] "GET /validate/spectre HTTP/1.1" 200 1125 "http://hassio-ip:3474/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.55"
[2022-03-28 22:01:21] production.DEBUG: Now in App\Http\Controllers\IndexController::postIndex  
[2022-03-28 22:01:21] production.DEBUG: nordigen is a valid flow, redirect to authenticate.  
192.168.10.26 - - [28/Mar/2022:22:01:21 +0200] "POST / HTTP/1.1" 302 1952 "http://hassio-ip:3474/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.55"
[2022-03-28 22:01:21] production.DEBUG: Now in AuthenticateController, calling middleware.  
[2022-03-28 22:01:21] production.DEBUG: isReadyForNordigenStep("authenticate")  
[2022-03-28 22:01:21] production.DEBUG: isReadyForNordigenStep: Return true  
[2022-03-28 22:01:21] production.DEBUG: Now at App\Services\Nordigen\AuthenticationValidator::validate  
[2022-03-28 22:01:21] production.DEBUG: Now at App\Services\Nordigen\TokenManager::hasValidRefreshToken  
[2022-03-28 22:01:21] production.DEBUG: No Nordigen refresh token, so return false.  
[2022-03-28 22:01:21] production.DEBUG: Now at App\Services\Nordigen\TokenManager::hasExpiredRefreshToken  
[2022-03-28 22:01:21] production.DEBUG: No refresh token, so return false.  
[2022-03-28 22:01:21] production.DEBUG: Now at App\Services\Nordigen\TokenManager::getNewTokenSet  
192.168.10.26 - - [28/Mar/2022:22:01:21 +0200] "GET /authenticate HTTP/1.1" 302 1579 "http://hassio-ip:3474/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.55"
[2022-03-28 22:01:21] production.DEBUG: isReadyForNordigenStep("upload-files")  
[2022-03-28 22:01:21] production.DEBUG: isReadyForNordigenStep: Return true  
[2022-03-28 22:01:21] production.DEBUG: Now at App\Http\Controllers\Import\UploadController::index  
[2022-03-28 22:01:21] production.ERROR: Impossible to create the root directory "/config/addons_config/fireflyiii_data_importer/configurations".  {"exception":"[object] (League\\Flysystem\\Exception(code: 0): Impossible to create the root directory \"/config/addons_config/fireflyiii_data_importer/configurations\".  at /var/www/html/vendor/league/flysystem/src/Adapter/Local.php:112)
[stacktrace]
#0 /var/www/html/vendor/league/flysystem/src/Adapter/Local.php(78): League\\Flysystem\\Adapter\\Local->ensureDirectory()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemManager.php(182): League\\Flysystem\\Adapter\\Local->__construct()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemManager.php(147): Illuminate\\Filesystem\\FilesystemManager->createLocalDriver()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemManager.php(115): Illuminate\\Filesystem\\FilesystemManager->resolve()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemManager.php(78): Illuminate\\Filesystem\\FilesystemManager->get()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Filesystem\\FilesystemManager->disk()
#6 /var/www/html/app/Http/Controllers/Import/UploadController.php(71): Illuminate\\Support\\Facades\\Facade::__callStatic()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Import\\UploadController->index()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\\Routing\\Route->run()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#13 /var/www/html/app/Http/Middleware/IsReadyForStep.php(54): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\UploadControllerMiddleware->handle()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(723): Illuminate\\Pipeline\\Pipeline->then()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(698): Illuminate\\Routing\\Router->runRouteWithinStack()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRoute()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(651): Illuminate\\Routing\\Router->dispatchToRoute()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#45 /var/www/html/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#49 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#51 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#52 /var/www/html/public/index.php(77): Illuminate\\Foundation\\Http\\Kernel->handle()
#53 {main}
"} 
```

**Comment by alexbelgium** [comment]
What is really strange is that I can't replicate what you see... For example if I open the webui of the -4, here is what I see (I don't have a stable Fireflyiii instance which could explain the authentification error)

<img width="496" alt="image" src="https://user-images.githubusercontent.com/44178713/160555508-01a92c8b-3c1b-4374-b8e8-c597a7d1bfe1.png">

**Comment by diamant-x** [comment]
Ok, I got some progress.
I reconstructed the Addon. Still failed.
Uninstalled the Addon, deleted the addons_config folder, installed the addon, added the addon config in hassio, started the addon (Folder were created by addon), added the files. Failed again.
Deleted the 'configuration' folder (within the addon_config/firefly...importer/ path). -> Didn't failed!
Of course it was empty so i added back the config files to that folder. Failed again.

I'm copying the files using SMB from a windows machine using the official samba addon (Current version: 9.5.1). I don't recall changing anything else on my configuration.
I tried also using the FTP addon method with same error fail.
I tried getting in a cmd on the container instance and doing 'touch filename' to force modify it with the container's user just in case. Same error.

Not sure why, but now suddenly it doesn't like files there :S

**Comment by alexbelgium** [comment]
Thanks, I'll try to replicate but don't have much time for the moment

**Comment by alexbelgium** [comment]
It's crazy but I can't even install a full system to authenticate ;-) So I've generated a PAT in Firefly, put it in the Firefly Data Importer, but still have a 401 error when starting the addon... It's like "https://github.com/firefly-iii/firefly-iii/discussions/5580". Do you see the same?

**Comment by alexbelgium** [comment]
OK once mystery solved, I've pushed a new version without the 401 bug. Now I can access the ui and will test the rest

**Comment by alexbelgium** [comment]
So with the latest version, I have tested :
- Addon starts without error
- WebUI can be accessed and navigated
- WebUI allows to upload a fake csv file that I found on internet.

For configuration, I've created a blank file in the configurations folder and don't see an error message at addon startup.

I'll continue some tests but I don't see critical issues in the latest version

**Comment by diamant-x** [comment]
Thanks.
I have installed it and so far it looks good.
My workaround though was to have:
 - No files in configuration/ folder
 - Files only in import folder.
Restart the addon with the above 2 conditions, and then the UI would work, and the auto-cron import would also pick up the import files and update it.

Thanks!

**Comment by alexbelgium** [comment]
Strange, I've created a blank file and the configurations folder and it still starts. Well, as long as it works and you're happy that's the most important :) can I close it or do you use configurations?

Thanks!

**Comment by alexbelgium** [comment]
Thanks for all the troubleshooting infos, enjoy :)
