### ISSUE TITLE
[Jellyfin] Can't start the addon

### ISSUE THREAD

**Issue by txitxo0** [alexbelgium/hassio-addons#399]
**Which addon?**
- Addon name : Jellyfin
- Addon version : 10.8.1-1-ls170

**Describe the bug**

The addon was working good in previous versions (But I can't assure in wich one, I didn't run it from a month ago, but I was updating it anyway).

Just try to start the addon and it stack at "00-banner.sh : executing"

I tried rebuilding the addon, but didn't work (just figuring out it could be something wron in the container)
Checking the logm two packages got time out s6-rc: fatal and s6-sudoc

**To Reproduce**

1. Go to the addon
2. Click on start
4. See error -->

**Full addon log**

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service 00-legacy: starting
s6-rc: info: service 00-legacy successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-aaa_dockerfile_backup.sh
Executing modules script : 00-banner.sh 92-local_mounts.sh 92-smb_mounts.sh
Get:1 http://ppa.launchpad.net/ubuntu-raspi2/ppa-nightly/ubuntu focal InRelease [18.1 kB]
Get:2 http://ports.ubuntu.com/ubuntu-ports focal InRelease [265 kB]
Get:3 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease [114 kB]
Get:4 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease [108 kB]
Get:5 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease [114 kB]
Get:6 https://repo.jellyfin.org/ubuntu focal InRelease [6636 B]
Get:7 http://ppa.launchpad.net/ubuntu-raspi2/ppa-nightly/ubuntu focal/main armhf Packages [1553 B]
Get:8 http://ports.ubuntu.com/ubuntu-ports focal/restricted armhf Packages [10.8 kB]
Get:9 http://ports.ubuntu.com/ubuntu-ports focal/main armhf Packages [1227 kB]
Get:10 http://ports.ubuntu.com/ubuntu-ports focal/multiverse armhf Packages [141 kB]
Get:11 http://ports.ubuntu.com/ubuntu-ports focal/universe armhf Packages [10.9 MB]
Get:12 https://fra1.mirror.jellyfin.org/ubuntu focal/main armhf Packages [1891 B]
Get:13 http://ports.ubuntu.com/ubuntu-ports focal-updates/main armhf Packages [1353 kB]
Get:14 http://ports.ubuntu.com/ubuntu-ports focal-updates/universe armhf Packages [958 kB]
Get:15 http://ports.ubuntu.com/ubuntu-ports focal-updates/restricted armhf Packages [16.9 kB]
Get:16 http://ports.ubuntu.com/ubuntu-ports focal-updates/multiverse armhf Packages [9594 B]
Get:17 http://ports.ubuntu.com/ubuntu-ports focal-backports/universe armhf Packages [27.1 kB]
Get:18 http://ports.ubuntu.com/ubuntu-ports focal-backports/main armhf Packages [53.7 kB]
Get:19 http://ports.ubuntu.com/ubuntu-ports focal-security/multiverse armhf Packages [4736 B]
Get:20 http://ports.ubuntu.com/ubuntu-ports focal-security/main armhf Packages [992 kB]
Get:21 http://ports.ubuntu.com/ubuntu-ports focal-security/restricted armhf Packages [16.6 kB]
Get:22 http://ports.ubuntu.com/ubuntu-ports focal-security/universe armhf Packages [685 kB]
Fetched 17.1 MB in 8s (2036 kB/s)
s6-rc: fatal: timed out
s6-sudoc: fatal: unable to get exit status from server: Operation timed out
Reading package lists...
00-banner.sh
92-local_mounts.sh
92-smb_mounts.sh
Executing dependency script with custom elements : nginx
-----------------------------------------------------------
 Add-on: Jellyfin NAS
 A Free Software Media System that puts you in control of managing and streaming your media.
-----------------------------------------------------------
 Add-on version: 10.8.1-1-ls170
 You are running the latest version of this add-on.
 System: Raspbian GNU/Linux 10 (buster)  (armv7 / raspberrypi4)
 Home Assistant Core: 2022.7.5
 Home Assistant Supervisor: 2022.07.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
 https://github.com/alexbelgium/hassio-addons
-----------------------------------------------------------
92-smb_mounts.sh : executing
92-local_mounts.sh : executing
00-banner.sh : executing
```

**Full addon config**

```
PGID: 0
PUID: 0
data_location: /config/addons_config/jellyfin
```

**System**

Raspberry Pi 4 4GB with Raspbian GNU/Linux 10 (buster). Home assistan in a docker installation

- Supervisor version: supervisor-2022.07.0
- Host system version: core-2022.7.5

**Comment by alexbelgium** [comment]
Hi, I can't replicate, it starts fine for me. It is strange that it times out. Does the launch sequence takes longer than 5 min, which is the setting for timeout?

**Comment by txitxo0** [comment]
Hi again, 

It does'nt usually takes more than 5 minutes, but now it just stack at 00-banner.sh : executing, so yes... now it issn't start never. I didnt edit anything special in the system so the timeout should be the standar 60, but in the logs feels like it just thorugth the timeout no waiting for it.

I manually uninstall the addon, purge my system for all the jellyfin images I had from previous updates. An, install the addon again (this time with the latest version from this early morning 10.8.1-1-ls170-2

The issue remains in the same state :S I don't know what is happening
Log:
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service 00-legacy: starting
s6-rc: info: service 00-legacy successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-aaa_dockerfile_backup.sh
Executing modules script : 00-banner.sh 92-local_mounts.sh 92-smb_mounts.sh
Get:1 http://ppa.launchpad.net/ubuntu-raspi2/ppa-nightly/ubuntu focal InRelease [18.1 kB]
Get:2 http://ports.ubuntu.com/ubuntu-ports focal InRelease [265 kB]
Get:3 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease [114 kB]
Get:4 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease [108 kB]
Get:5 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease [114 kB]
Get:6 http://ppa.launchpad.net/ubuntu-raspi2/ppa-nightly/ubuntu focal/main armhf Packages [1553 B]
Get:7 https://repo.jellyfin.org/ubuntu focal InRelease [6636 B]
Get:8 http://ports.ubuntu.com/ubuntu-ports focal/restricted armhf Packages [10.8 kB]
Get:9 http://ports.ubuntu.com/ubuntu-ports focal/universe armhf Packages [10.9 MB]
Get:10 http://ports.ubuntu.com/ubuntu-ports focal/multiverse armhf Packages [141 kB]
Get:11 http://ports.ubuntu.com/ubuntu-ports focal/main armhf Packages [1227 kB]
Get:12 http://ports.ubuntu.com/ubuntu-ports focal-updates/main armhf Packages [1353 kB]
Get:13 http://ports.ubuntu.com/ubuntu-ports focal-updates/universe armhf Packages [958 kB]
Get:14 http://ports.ubuntu.com/ubuntu-ports focal-updates/restricted armhf Packages [16.9 kB]
Get:15 http://ports.ubuntu.com/ubuntu-ports focal-updates/multiverse armhf Packages [9594 B]
Get:16 http://ports.ubuntu.com/ubuntu-ports focal-backports/universe armhf Packages [27.1 kB]
Get:17 http://ports.ubuntu.com/ubuntu-ports focal-backports/main armhf Packages [53.7 kB]
Get:18 http://ports.ubuntu.com/ubuntu-ports focal-security/universe armhf Packages [685 kB]
Get:19 http://ports.ubuntu.com/ubuntu-ports focal-security/multiverse armhf Packages [4736 B]
Get:20 http://ports.ubuntu.com/ubuntu-ports focal-security/restricted armhf Packages [16.6 kB]
Get:21 http://ports.ubuntu.com/ubuntu-ports focal-security/main armhf Packages [992 kB]
Get:22 https://fra1.mirror.jellyfin.org/ubuntu focal/main armhf Packages [1891 B]
Fetched 17.1 MB in 4s (3844 kB/s)
Reading package lists...
s6-rc: fatal: timed out
s6-sudoc: fatal: unable to get exit status from server: Operation timed out
00-banner.sh
92-local_mounts.sh
92-smb_mounts.sh
Executing dependency script with custom elements : nginx
-----------------------------------------------------------
 Add-on: Jellyfin NAS
 A Free Software Media System that puts you in control of managing and streaming your media.
-----------------------------------------------------------
 Add-on version: 10.8.1-1-ls170-2
 You are running the latest version of this add-on.
 System: Raspbian GNU/Linux 10 (buster)  (armv7 / raspberrypi4)
 Home Assistant Core: 2022.7.5
 Home Assistant Supervisor: 2022.07.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
 https://github.com/alexbelgium/hassio-addons
-----------------------------------------------------------
92-smb_mounts.sh : executing
92-local_mounts.sh : executing
00-banner.sh : executing
```

**Comment by alexbelgium** [comment]
What changed is how HA interprets and manages s6 from addons. I had solved this for other addons but this is a strange issue I can't replicate yet.

**Comment by txitxo0** [comment]
I am trying to use the image from linuxserver.io directly as a container in my SO, no through HA. And I am experimenting problems too, so I guess it is more related to the image than the addon or HA

**Comment by txitxo0** [comment]
So weird, it is happening rares thing with others addons too. Plex media server and Emby don't show me any config to configure in the config tab. And Emby doesn't finish to be installed. So, I don't know what is happening

**Comment by txitxo0** [comment]
Yep, I am sure it is not a faulty system. Everything is working as expected except for this addon, and further more, in order to avoid this problem, I am use SSD drive instead of a common SD

But apparently it is a weird behaviour for my non typical SO

**Comment by alexbelgium** [comment]
I've pushed a v3 disabling the wait time, let's see

**Comment by txitxo0** [comment]
Still nothing, the log is exactly the same, with the same time out error :s
I can't understand what is happening :S 
```
s6-rc: fatal: timed out
s6-sudoc: fatal: unable to get exit status from server: Operation timed out
```

I don't know if those are the root cause even, so... I know nothing

**Comment by alexbelgium** [comment]
> same issue also happening in (rpi4 4gb) after core 2022.7.5 update, at boot they not start but after restart addon they work normally. Also randomly stop working after restart.

Hi, txitxo0 issue is that he is using (probably) a supervised system that doesn't support curl at build. Apps are installed at start of the container start, which seem to cause an issue.

Could you please post your full addon log including the error message to check if you have the same issue? Thanks.

**Comment by alexbelgium** [comment]
> Still nothing, the log is exactly the same, with the same time out error :s I can't understand what is happening :S
> 
> ```
> s6-rc: fatal: timed out
> s6-sudoc: fatal: unable to get exit status from server: Operation timed out
> ```
> 
> I don't know if those are the root cause even, so... I know nothing
> 
> In the meanwhile, I will use Plex, but I will still try to run both Emby and its fork (and the one I like the most) Jellyfin

Thanks. I run daily Emby and it is perfectly stable. You don't have issues running it? It's strange as the script is the same, so it would be an interesting info.

**Comment by txitxo0** [comment]
> > Still nothing, the log is exactly the same, with the same time out error :s I can't understand what is happening :S
> > 
> > ```
> > s6-rc: fatal: timed out
> > s6-sudoc: fatal: unable to get exit status from server: Operation timed out
> > ```
> > 
> > I don't know if those are the root cause even, so... I know nothing
> > 
> > In the meanwhile, I will use Plex, but I will still try to run both Emby and its fork (and the one I like the most) Jellyfin
> 
> Thanks. I run daily Emby and it is perfectly stable. You don't have issues running it? As the script is the same, so it would be an interesting info. 

It is weird, the problem I face with emby addon is in the install. It just keep installing forever in a loop. Where can I check logs for the installation status?

**Comment by alexbelgium** [comment]
Logs during installation should be the ones in the [supervisor logs](https://www.home-assistant.io/integrations/system_log/).

You'll see something like 'starting build' and then potential errors in red.

Btw, I would love to build images for all addons but for that a dev needs to solve this bug : https://github.com/home-assistant/supervisor/issues/3414 (I've tried everything and couldn't find a way to obtain a response from a dev)

**Comment by alexbelgium** [comment]
I've had another idea (not very probably but still) so I've pushed a new code that sets chmod +x on all scripts to see if it helps. At the very least it will make the code more robust ;-) All addons (image based) are being rebuild with that

**Comment by alexbelgium** [comment]
Could you please also try to change puid and guid from 0 to 1000 to see if it makes a difference? Thanks

**Comment by alexbelgium** [comment]
It won't work. I've done another test, could you please try? Thanks

**Comment by txitxo0** [comment]
I have time to test, but I already see the other thread talking about the same and.......
YES! it works for me to! 
So much than you, awesome work, even better taking in account you couldn't replicate the error  🎉 🎉 🎉

**Comment by txitxo0** [comment]
> > Still nothing, the log is exactly the same, with the same time out error :s I can't understand what is happening :S
> > ```
> > s6-rc: fatal: timed out
> > s6-sudoc: fatal: unable to get exit status from server: Operation timed out
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I don't know if those are the root cause even, so... I know nothing
> > In the meanwhile, I will use Plex, but I will still try to run both Emby and its fork (and the one I like the most) Jellyfin
> 
> Thanks. I run daily Emby and it is perfectly stable. You don't have issues running it? As the script is the same, so it would be an interesting info.

Talking about emby, it is still the same, it just try to install it but fall in a loop just "installing" (having jellyfin addon stopped)
The supervisor log says:
```
22-07-20 21:35:19 INFO (MainThread) [supervisor.addons] Creating Home Assistant add-on data folder /data/addons/data/db21ed7f_emby_nas
22-07-20 21:35:19 INFO (MainThread) [supervisor.host.apparmor] Adding/updating AppArmor profile: db21ed7f_emby_nas
22-07-20 21:35:19 INFO (SyncWorker_4) [supervisor.docker.addon] Starting build for db21ed7f/armv7-addon-emby_nas:4.8.0.6
22-07-20 21:39:47 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
22-07-20 21:39:47 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_FAILED/ContextType.DNS_SERVER
22-07-20 21:39:47 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
22-07-20 21:39:47 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_IPV6_ERROR/ContextType.DNS_SERVER
22-07-20 21:39:47 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
22-07-20 21:39:47 WARNING (MainThread) [supervisor.addons.options] Option 'anonymous' does not exist in the schema for Mosquitto broker (core_mosquitto)
22-07-20 21:39:48 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
22-07-20 21:39:48 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
22-07-20 21:39:48 INFO (MainThread) [supervisor.resolution.check] System checks complete
22-07-20 21:39:48 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-07-20 21:39:48 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-07-20 21:39:48 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
22-07-20 21:39:48 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
22-07-20 21:40:15 WARNING (MainThread) [supervisor.addons.options] Option 'anonymous' does not exist in the schema for Mosquitto broker (core_mosquitto)
22-07-20 21:41:17 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
```
Just this, no errors and nothing more appears
