### ISSUE TITLE
🐛 [Spotweb] CSS (and maybe more) breaks via Nabu Casa

### ISSUE THREAD

**Issue by fbloemhof** [alexbelgium/hassio-addons#408]
**Which addon?**

- Addon name : Spotweb
- Addon version : 1.5.1-18

**Describe the bug**
When I'm connected to HA using my Nabu Casa URL the first page of Spotweb loads fine but selecting a filter breaks the layout, the CSS is not found (404).

Seeing some errors in DevTools, it looks like the URI gets a double entry (twice `api/hassio_ingress/[redacted]`).

`GET https://[redacted].ui.nabu.casa/api/hassio_ingress/[redacted]/api/hassio_ingress/[redacted]/?page=statics&type=css&mod=1658843593 net::ERR_ABORTED 404 (Not Found)
[redacted].ui.nabu.casa/:268`

`GET https://[redacted].ui.nabu.casa/api/hassio_ingress/[redacted]/api/hassio_ingress/[redacted]/?page=statics&type=js&lang=nl_NL&mod=1658843593 net::ERR_ABORTED 404 (Not Found)
?page=index&search[tree]=cat0_z2_c11&search[value][]=NULL:271`
        
`Uncaught ReferenceError: initSpotwebJs is not defined at ?page=index&search[tree]=cat0_z2_c11&search[value][]=NULL:271:13`

**To Reproduce**

**Full addon log**
`2022/07/29 16:11:48 [error] 268#268: *1109 "/app/api/hassio_ingress/[redacted]/index.php" is not found (2: No such file or directory), client: 127.0.0.1, server: _, request: "GET /api/hassio_ingress/[redacted]/?page=statics&type=css&mod=1658843593 HTTP/1.1", host: "[redacted].ui.nabu.casa", referrer: "https://[redacted].ui.nabu.casa/api/hassio_ingress/[redacted]/?page=index&search[tree]=cat0_z2_c11&search[value][]=NULL"
2022/07/29 16:11:48 [error] 268#268: *1111 "/app/api/hassio_ingress/[redacted]/index.php" is not found (2: No such file or directory), client: 127.0.0.1, server: _, request: "GET /api/hassio_ingress/[redacted]/?page=statics&type=js&lang=nl_NL&mod=1658843593 HTTP/1.1", host: "[redacted].ui.nabu.casa", referrer: "https://[redacted].ui.nabu.casa/api/hassio_ingress/[redacted]/?page=index&search[tree]=cat0_z2_c11&search[value][]=NULL"`

**Full addon config**

**System**

- Supervisor version: 2022.07.0
- Host system version: Home Assistant 2022.7.7

**Comment by alexbelgium** [comment]
Hi, is this new from the latest version of the addon? Or had always existed?

**Comment by fbloemhof** [comment]
I'm a new user so for me it was always existing, but I only used this version.

**Comment by alexbelgium** [comment]
Mmh I can't replicate... I'll do some more tests.

**Comment by alexbelgium** [comment]
Is it still occurring ? I could not replicate

**Comment by fbloemhof** [comment]
Can't notice any difference. Completely reinstalling the addon also made no difference.

Still seeing the /app/api references in the logging.

**Comment by alexbelgium** [comment]
Hi, I've pushed a new version to see if it helps

**Comment by fbloemhof** [comment]
That seems to break ngnix:

[11:37:25] INFO: Starting NGinx...
nginx: [emerg] invalid variable name in /etc/nginx/servers/ingress.conf:52
s6-svscanctl: fatal: unable to control /var/run/s6/services: No such
file or directory



Op ma 8 aug. 2022 om 07:08 schreef Alexandre ***@***.***>:

**Comment by alexbelgium** [comment]
Thanks, I'll revert

**Comment by alexbelgium** [comment]
I've tried another thing and checked that the addon starts. However as I can't replicate I can't check if it works

**Comment by fbloemhof** [comment]
Issue still exists...

Are you using Nabu Casa to test the issue?

**Comment by fbloemhof** [comment]
I think there is a slight difference, because Nabu Casa uses some sort reverse proxy to connect (don't know the exact details). 

I bought you some coffee's so you can test with it. :D

**Comment by alexbelgium** [comment]
Thanks very much. I'm on holidays without my pc but I'll check this ASAP when I come back in 2 weeks. Btw, any chances related to ingress requires a browser cache flush to be taken into account after updating

**Comment by fbloemhof** [comment]
Take your time, enjoy your holidays and the coffee!

**Comment by alexbelgium** [comment]
Hi, thanks for your contribution! I've taken a nabu casa subscription and understand now the source of issue : a nabu casa address doesn't have a visible port and this seems to cause issues. I've pushed a new version that seems to work on my temporary address. Please make sure to clear your browser cache (or use incognito mode) to check if it makes a difference! Thanks!

**Comment by fbloemhof** [comment]
This looks promising! Will do some further testing later.
