### ISSUE TITLE
🐛 [RESILIOSYNC] Write permission denied - readonly

### ISSUE THREAD

**Issue by AzonInc** [alexbelgium/hassio-addons#466]
**Which addon?**

- Addon name : ResilioSync
- Addon version : 2.7.3.1381-4

**Describe the bug**

I don't have Permissions to create or select Directories in Resilio Syncs UI. It seems like all the Directories are ReadOnly.
The Button to create a new Directory is disabled and whenever I try to create a new Directory it errors with permission denied.
All settings are the default ones.

![image](https://user-images.githubusercontent.com/11911587/188696914-4489a60f-5f88-464a-912d-15d1bd490099.png)
![image](https://user-images.githubusercontent.com/11911587/188698696-26f9ff89-7ce6-4ddd-9d2b-60e11a39e9e5.png)

**To Reproduce**

1. Install Addon
2. Start Resilio Sync
3. Open Web UI
4. Basic Setup (Username + Password)
5. Try to create new Folder

**Full addon log**

> -----------------------------------------------------------
>  Add-on: ResilioSync
>  Self-hosted file share and collaboration platform on the web
> -----------------------------------------------------------
>  Add-on version: 2.7.3.1381-4
>  You are running the latest version of this add-on.
>  System: Home Assistant OS 8.5  (aarch64 / raspberrypi4-64)
>  Home Assistant Core: 2022.8.7
>  Home Assistant Supervisor: 2022.08.5
> -----------------------------------------------------------
>  Please, share the above information when looking for help
>  or support in, e.g., GitHub, forums
>  https://github.com/alexbelgium/hassio-addons
> -----------------------------------------------------------
> cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
> cont-init: info: running /etc/cont-init.d/00-folders.sh
> Adapting files
> [18:57:30] INFO: Setting config_location to /config/addons_config/resioliosync
> sed: can't read /etc/cont-init.d/10-adduser: No such file or directory
> Checking if folders exist
> Setting ownership to 0:0
> [18:57:31] INFO: Setting data_location to /share/resioliosync
> Adapting files
> sed: no input files
> sed: can't read /etc/cont-init.d/10-adduser: No such file or directory
> Checking if folders exist
> Setting ownership to 0:0
> cont-init: info: /etc/cont-init.d/00-folders.sh exited 0
> cont-init: info: running /etc/cont-init.d/01-envfile
> cont-init: info: /etc/cont-init.d/01-envfile exited 0
> cont-init: info: running /etc/cont-init.d/01-migrations
> [migrations] started
> [migrations] no migrations found
> cont-init: info: /etc/cont-init.d/01-migrations exited 0
> cont-init: info: running /etc/cont-init.d/30-config
> cont-init: info: /etc/cont-init.d/30-config exited 0
> cont-init: info: running /etc/cont-init.d/90-custom-folders
> cont-init: info: /etc/cont-init.d/90-custom-folders exited 0
> cont-init: info: running /etc/cont-init.d/90-ingress.sh
> cont-init: info: /etc/cont-init.d/90-ingress.sh exited 0
> cont-init: info: running /etc/cont-init.d/92-local_mounts.sh
> cont-init: info: /etc/cont-init.d/92-local_mounts.sh exited 0
> cont-init: info: running /etc/cont-init.d/92-smb_mounts.sh
> cont-init: info: /etc/cont-init.d/92-smb_mounts.sh exited 0
> cont-init: info: running /etc/cont-init.d/99-custom-scripts
> [custom-init] no custom files found, skipping...
> cont-init: info: /etc/cont-init.d/99-custom-scripts exited 0
> s6-rc: info: service legacy-cont-init successfully started
> s6-rc: info: service init-mods: starting
> s6-rc: info: service init-mods successfully started
> s6-rc: info: service init-mods-package-install: starting
> s6-rc: info: service init-mods-package-install successfully started
> s6-rc: info: service init-mods-end: starting
> s6-rc: info: service init-mods-end successfully started
> s6-rc: info: service init-services: starting
> s6-rc: info: service init-services successfully started
> s6-rc: info: service legacy-services: starting
> services-up: info: copying legacy longrun nginx (no readiness notification)
> services-up: info: copying legacy longrun resilio (no readiness notification)
> s6-rc: info: service legacy-services successfully started
> s6-rc: info: service 99-ci-service-check: starting
> [ls.io-init] done.
> s6-rc: info: service 99-ci-service-check successfully started
> [20220906 19:05:09.342] Debug log mask has been set to FFFFFFFF
> [20220906 19:05:09.343] Features mask has been set to 0
> [20220906 19:05:09.345] ZIP: Can't locate [version] in zip, error -100.
> [20220906 19:05:09.346] Configuration from file "/config/addons_config/resioliosync/sync.conf" has been applied

**Full addon config**

> PGID: 0
> PUID: 0
> config_location: /config/addons_config/resioliosync
> data_location: /share/resioliosync

**System**

Home Assistant 2022.8.7
Supervisor 2022.08.5
Operating System 8.5

**Comment by AzonInc** [comment]
I tried to create and edit files inside the addon container which is working fine.
However the resilio sync process is running unter the user "abc" and the created sub-folders belong to "root".

Even when PUID and PGID are 0, the user abc is used instead of root.

> root@db21ed7f-resiliosync:/share# ls -la
```
drwxr-xr-x 3 root root 4096 Mar 11 08:33 .
drwxr-xr-x 4 root root 4096 Sep  6 20:18 ..
drwxr-xr-x 6 abc  abc  4096 Sep  6 20:20 resiliosync
```

> root@db21ed7f-resiliosync:/share/resiliosync# ls -la
```
drwxr-xr-x 2 root root 4096 Sep  6 20:13 downloads
drwxr-xr-x 2 root root 4096 Sep  6 20:13 folders
drwxr-xr-x 2 root root 4096 Sep  6 20:13 mounted_folders
```

**Comment by alexbelgium** [comment]
Hi, my understanding is that what is important is the PUID and PGID and that multiple users (including root) can share it
I had a bug in the Dockerfile instructions that removed all /config files, preventing the application of permissions

Normally in the newly pushed version everything is solved

**Comment by maivorbim** [comment]
Hello, I have the same issue with 2.7.3.1381-4-bugfix. Running home assistant 2022.9.1 with PGID and PUID set to 0. The latest bugfix version does not throw an error when selecting the folders and it starts syncing the files with an external device, however no files are written in the shared folders.

**Comment by AzonInc** [comment]
@maivorbim what do you mean by shared folders?
@alexbelgium File Permissions are fine now, however changing `data_location` is still not working.
When chaning it, new directories are created on the new path but the mounts to the container seem to not work properly.
The sync.conf never changes. So I guess mounts are used for the directories to point to the filesystem outside of the container.

Would be great if the sync.conf file is changed when using local disks to use /mnt/sda1 for example.
I changed the sync.conf manually to point to /mnt/sda1 which is working perfectly.
Also the Possibility to disable the whitelist would be nice, because most people don't need the default folders and want to use ttheir own file structure on mounted disks.

**Comment by maivorbim** [comment]
Shared folders by resiliosync. i.e. the ones in data_location setting: /media/backup/test

**Comment by alexbelgium** [comment]
Thanks, I'll look at it!

**Comment by alexbelgium** [comment]
> @maivorbim what do you mean by shared folders? @alexbelgium File Permissions are fine now, however changing `data_location` is still not working. When chaning it, new directories are created on the new path (outside of the container) but the mounts to the container seem to not work properly. The sync.conf never changes. So I guess mounts are used for the directories to point to the filesystem outside of the container.
> 
> Would be great if the sync.conf file is changed when using local disks to use /mnt/sda1 for example. I changed the sync.conf manually to point to /mnt/sda1 which is working perfectly. Also the Possibility to disable the whitelist would be nice, because most people don't need the default folders and want to use ttheir own file structure on mounted disks.

Hi, thanks! I'm not used to resioliosync. I've looked at the [documentation] (https://help.resilio.com/hc/en-us/articles/206178884#overview) page and am confused. Does deleting the whitelist parameter is enough? Or should the data_location be added to it? Thanks

**Comment by alexbelgium** [comment]
Having (superficially) read the documentation, I have made changes to the default configuration file. You should be able to make those changes manually in the sync.conf file located in your config folder defined in the addons options

**Comment by maivorbim** [comment]
not stale

**Comment by maivorbim** [comment]
Yes, the current error it gives on a fresh install is:

cont-init: info: /etc/cont-init.d/92-local_mounts.sh exited 0
cont-init: info: running /etc/cont-init.d/92-smb_mounts.sh
cont-init: info: /etc/cont-init.d/92-smb_mounts.sh exited 0
cont-init: info: running /etc/cont-init.d/99-custom-files
[custom-init] No custom files found, skipping...
cont-init: info: /etc/cont-init.d/99-custom-files exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-mods: starting
s6-rc: info: service init-mods successfully started
s6-rc: info: service init-mods-package-install: starting
s6-rc: info: service init-mods-package-install successfully started
s6-rc: info: service init-mods-end: starting
s6-rc: info: service init-mods-end successfully started
s6-rc: info: service init-services: starting
s6-rc: info: service init-services successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun nginx (no readiness notification)
services-up: info: copying legacy longrun resilio (no readiness notification)
[20220930 16:30:53.484] Can't parse config file "/config/addons_config/resiliosync/sync.conf": "Error while opening config file /config/addons_config/resiliosync/sync.conf"
[20220930 16:30:53.484] Can't parse config file "/config/addons_config/resiliosync/sync.conf": "Error while opening config file /config/addons_config/resiliosync/sync.conf"
s6-rc: info: service legacy-services successfully started
s6-rc: info: service 99-ci-service-check: starting
Error while opening config file /config/addons_config/resiliosync/sync.confError while opening config file /config/addons_config/resiliosync/sync.conf[ls.io-init] done.
s6-rc: info: service 99-ci-service-check successfully started
[20220930 16:30:54.504] Can't parse config file "/config/addons_config/resiliosync/sync.conf": "Error while opening config file /config/addons_config/resiliosync/sync.conf"
[20220930 16:30:54.505] Can't parse config file "/config/addons_config/resiliosync/sync.conf": "Error while opening config file /config/addons_config/resiliosync/sync.conf"
[20220930 16:30:55.505] Can't parse config file "/config/addons_config/resiliosync/sync.conf": "Error while opening config file /config/addons_config/resiliosync/sync.conf"

the sync.conf file is not being created anymore.

**Comment by alexbelgium** [comment]
Mmh now it should work again

**Comment by maivorbim** [comment]
Looks like it is working again! Fresh install, permissions seem fine, files are being synced, folder are being written. Great job, Alex, thank you 👍

**Comment by alexbelgium** [comment]
Great, thanks for the feedback!
