### ISSUE TITLE
[nextcloud] suppress crond console output?

### ISSUE THREAD

**Issue by blairun** [alexbelgium/hassio-addons#752]
**Which addon?**
nextcloud

**Describe the solution you'd like**
Hi. I've noticed that when the nextcloud addon is running, it prints crond logs to the home assistant os console.  It quickly fills up the console and interrupts commands that are being typed there.  Is there a way to suppress this output?  I'm not sure whether this is linked to the addon or the original app, so please point me in a better direction if needed.

![Screenshot](https://user-images.githubusercontent.com/1585872/223603241-820a1b8b-1cc0-403e-a190-2843980e82d1.png)

**Comment by alexbelgium** [comment]
Hi, thanks this is due to the addon but not sure yet how to solve it

**Comment by alexbelgium** [comment]
Ok think I've solved it, I'll do a couple more tests before pushing a version

**Comment by alexbelgium** [comment]
I've pushed a version that should link logs from nginx, php and nextcloud to the addons console. Let's see if that works

**Comment by alexbelgium** [comment]
Many new permissions error though, wip

**Comment by alexbelgium** [comment]
Latest version channels php, cron and nginx logs through addon. Not sure about crond though, and i don't see the same messages that you see on HAos logs. Not sure how to check if the issues still occurs, but as it is probably linked to system the issue could still be present

**Comment by blairun** [comment]
Thanks for working on this!  After the updates, the issue is still present for me. I also created a new home assistant os vm and installed this nextcloud addon. That fresh install has the same issue.  cli on fresh vm:

![Screenshot](https://user-images.githubusercontent.com/1585872/223901132-bbefab6d-249e-4320-bb00-58501551e7e4.png)

**Comment by alexbelgium** [comment]
Thanks for the very relevant link! Indeed it seems a specific issue for VM systems... I can't replicate it on HA os which doesn't help in solving it. Well at least the changes I've made allow to redirect nginx and php to addon logs which is already an improvement to the addon (if not for your issue)

**Comment by alexbelgium** [comment]
Wrong button ;)

**Comment by alexbelgium** [comment]
Should be good now

**Comment by blairun** [comment]
Yes, the issue is resolved for me.  Many thanks!
