### ISSUE TITLE
🐛 Omada update check fails

### ISSUE THREAD

**Issue by bezigebever** [alexbelgium/hassio-addons#847]
**Which addon?**

- Addon name : Omada
- Addon version : 5.9-chromium-amd64-2023-05-26

**Describe the bug**

Check for updates is not working.

**To Reproduce**

1. Go to Omada webpage
2. Click on Devices
3. Click on Check for updates

**Error log**

```
05-28-2023 10:41:18.109 INFO [comm-pool-14] [] c.t.s.o.m.c.b(): Checking Device Last Firmware...
05-28-2023 10:41:18.121 INFO [https-jsse-nio-8043-exec-9] [] c.t.s.c.l.a.AbstractReadWriteLockService(): [readWriteLockService]businessId:omadac.id:2c895d304ec02a2f7080b9c5cc413f45 get writeLock module:manager:upgrade.online.check fail, execute onFail.
```

**System**

- Home Assistant version: 2023.5.4
- Supervisor version: 2023.04.01
- Host system version: HassOS 10.1

**Comment by alexbelgium** [comment]
Not stale - just didn't had time yet to look

**Comment by alexbelgium** [comment]
There was a big issue with port incompatibility that I corrected in the latest build, did it change something?

**Comment by bezigebever** [comment]
It seems, instead of an update, I got a downgrade of the controller to 20230518.
Now I have a serious issue, I can't even access the GUI any more...
Stange is the mobile app is still working and shows everything is connected, I suppose it uses another port ?

**Comment by bezigebever** [comment]
I've just found out, the button in HA goes to port 8888, while the web gui runs on 8088 (or 8043).
Still got the update issue, but like said I got a roll-back to 20230518.

**Comment by bezigebever** [comment]
I'm now on 2023-06-05. WebGUI is OK.
Update check still failing.
`06-05-2023 18:49:26.211 INFO [https-jsse-nio-8043-exec-8] [] c.t.s.c.l.a.AbstractReadWriteLockService(): [readWriteLockService]businessId:omadac.id:2c895d304ec02a2f7080b9c5cc413f45 get writeLock module:manager:upgrade.online.check fail, execute onFail.`

**Comment by alexbelgium** [comment]
Thanks, actually I really don't have enough time to look closely. Therefore, I'll just revert to 5.9-chromium-amd64-2023-05-12 and pause updates until I have time

**Comment by bezigebever** [comment]
Any updates ?
